fixed the issue where adding an image that's not integration image as…
demisto/demisto-sdk pull request #1157
Opened 2021-03-07 15:54 UTC by merit-maita

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/34284

## Description
Fixed the issue where adding an image that's not integration image asks for a RN and a new version.

## Screenshots
Paste here any images that will help the reviewer

## Must have
- [ ] Tests
- [ ] Documentation

2021-03-07 17:55 UTC, ShahafBenYakir commented
What will happen for documentation images?

2021-03-08 00:55 UTC, yaakovi requested changes
add unit-tests:
* for find_type - an image named `Author_image.png` returned the expected type.
* for validate manager, added/modified author image doesn't fail the release notes validation.

2021-03-08 00:57 UTC, yaakovi commented
> @merit-maita @yaakovi What will happen for documentation (README) images?

doc images have their own file type DOC_IMAGE. their behavior should not be affected

2021-03-08 08:37 UTC, merit-maita commented
@ShahafBenYakir 
as @yaakovi mentioned, one more thing, every image that does not end with _image.png, is considered as DOC_IMG, and skipped automatically, as we saw in Guy's screenshot, and it exists in the DOC_FILES folder thats also ignored. the reason why the build you mentioned failed was because it ended with _image.png, so it was considered as an image that has an effect, but it's Author_image, so it had to be excluded

2021-03-08 22:10 UTC, yaakovi approved these changes

2021-03-08 22:10 UTC, yaakovi commented on demisto_sdk/commands/common/tests/tools_test.py
> +        ('Author_image.png', None)
```suggestion
        ('Author_image.png', None),
```

2021-03-09 10:13 UTC, merged