Demisto SDK Convert Command
demisto/demisto-sdk pull request #1325
Opened 2021-06-01 14:29 UTC by tomneeman151293

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/33529

## Description
Creating a new command to support conversion of entities such as Layouts/Classifiers between versions.

## Must have
- [x] Tests
- [x] Documentation

2021-06-06 06:28 UTC, dantavori requested changes
Great work!

2021-06-06 10:29 UTC, tomneeman151293 commented on demisto_sdk/commands/convert/README.md
> +```
We dont need them. I'll delete

2021-06-06 10:36 UTC, tomneeman151293 commented on demisto_sdk/commands/convert/converters/layout/layout_6_0_0_converter.py
> +            self.update_incident_types_related_to_old_layouts(old_corresponding_layouts, layout_id)
Should be. I'll add it

2021-06-06 11:03 UTC, tomneeman151293 commented on demisto_sdk/commands/convert/converters/layout/layout_up_to_5_9_9_converter.py
> +                                     layout.layout_id())]
Nope. This is an edge case. Talked to @ShahafBenYakir it was decided to not support such cases

2021-06-06 11:33 UTC, tomneeman151293 commented on demisto_sdk/commands/convert/converters/classifier/classifier_6_0_0_converter.py
> +                      type='mapping-incoming', description='TODO - Add description', version=-1,
After talking to @roysagi , he said the best would be to leave empty description.

2021-06-06 11:33 UTC, tomneeman151293 commented on demisto_sdk/commands/convert/converters/classifier/classifier_6_0_0_converter.py
> +                              description='TODO - Add description', fromVersion='6.0.0', id=classifier_name_and_id)
After talking to @roysagi , he said the best would be to leave empty description.

2021-06-10 16:37 UTC, roysagi requested changes
@tomneeman151293 - Great job this really looks good. I do have some notes:
1) we should try and mitigate the number of test files in the SDK in general, now you are adding about 20 more files - I think you should take another look and use the test suite instead.
2) do not use a prefix separate schema for testing use the real one - if someone breaks the schema and it breaks the command, then the schema change itself should break the unit tests associated with the command.

2021-06-10 16:37 UTC, roysagi commented on demisto_sdk/commands/convert/README.md
> +**Classifiers/Mappers conversion from 6.0.0 and above to versions 5.9.9 and below is currently not supported. Request for converting a pack for versions below 6.0.0 will result on layouts conversion
We should really create a simple list of what can be converted, something that is easy to read and gets the info out quickly the first time you approach the command.

2021-06-13 15:47 UTC, tomneeman151293 commented
@roysagi Managed to minimize some test files. There is still work to be done in TestSuite to make it more user friendly, (no funcs to mock classifier/layouts for example, while there is funcs to mock integration etc, which made it a bit difficult for me to mock)

2021-06-14 13:41 UTC, dantavori approved these changes

2021-06-15 08:19 UTC, roysagi approved these changes

2021-06-15 08:21 UTC, merged