Added `Author_image.png` into root base files when creating a pack.
demisto/demisto-sdk pull request #1346
Opened 2021-06-08 12:41 UTC by obenacot

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: #36569

## Description
Added `Author_image.png` into root base files when creating a pack.

## Screenshots
Paste here any images that will help the reviewer

## Must have
- [ ] Tests
- [ ] Documentation

2021-07-27 16:58 UTC, ShahafBenYakir commented on demisto_sdk/commands/common/hook_validations/pack_unique_files.py
> +        return True
We shouldn't validate these as part of the init. We only validate these kind of thing in the validate command

2021-07-28 05:31 UTC, yaakovi requested changes
your build is failing

2021-07-28 05:31 UTC, yaakovi commented on demisto_sdk/commands/common/tests/pack_unique_files_test.py
> +    def test_validate_pack_readme_file_is_not_empty_partner(self, mocker, result):
why did you change this?

2021-08-15 07:19 UTC, yaakovi requested changes
you haven't fixed my original comments.
fix the LGTM alert

2021-09-09 10:59 UTC, yaakovi approved these changes
fix the conflicts and merge

2021-11-02 18:28 UTC, merged