Contribution Management - Formatting on modified files only
demisto/demisto-sdk pull request #1360
Opened 2021-06-13 13:04 UTC by guyfreund

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/35912

## Description
Formatting without specifying an input pack, will run on modified files via git.

## Attached build on updated pack:
https://github.com/demisto/contribution-management/runs/2813735595?check_suite_focus=true

## Attached build on new pack:
https://github.com/demisto/contribution-management/runs/2784670854?check_suite_focus=true

2021-06-13 13:40 UTC, avidan-H commented
@guyfreund can you attach here as well the builds _without your change_ that would run on the same packs you used to demonstrate your changes? Basically, I want to better see the build pre-your-change vs. post-your-change for comparison.

2021-06-13 13:42 UTC, avidan-H requested changes

2021-06-13 13:42 UTC, avidan-H commented on demisto_sdk/commands/init/contribution_converter.py
> +        click.echo('Executing \'format\' on the restructured-contribution-zip new/modified files')
```suggestion
        click.echo('Executing \'format\' on the restructured contribution zip new/modified files at {self.pack_dir_path}')
```

2021-06-13 15:08 UTC, guyfreund commented
> @guyfreund can you attach here as well the builds _without your change_ that would run on the same packs you used to demonstrate your changes? Basically, I want to better see the build pre-your-change vs. post-your-change for comparison.

### Updated Pack - master
https://github.com/demisto/contribution-management/runs/2814149266?check_suite_focus=true
![image](https://user-images.githubusercontent.com/53565845/121812869-402d9800-cc72-11eb-80f2-256904e9f5b1.png)
You can see non-related files e.g. test data file and ut file
### New Pack - master
https://github.com/demisto/contribution-management/runs/2814150935?check_suite_focus=true

2021-06-14 06:34 UTC, avidan-H approved these changes

2021-06-14 06:55 UTC, merged