Validate fields name
demisto/demisto-sdk pull request #1370
Opened 2021-06-15 13:19 UTC by sabaghadar

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
validate incident field name prefix is pack name

## Screenshots
Paste here any images that will help the reviewer

## Must have
- [ ] Tests
- [ ] Documentation

2021-06-27 08:45 UTC, roysagi requested changes

2021-06-27 08:45 UTC, roysagi commented on demisto_sdk/commands/common/errors.py
> +               f"you can use the pack name or one of the prefixes in packe.metadat itemPrefix. Example: {pack_name} {field_name}." \
```suggestion
               f"you can use the pack name or one of the prefixes found in the itemPrefix field in the pack_metadata. Example: {pack_name} {field_name}." \
```

2021-06-27 08:45 UTC, roysagi commented on demisto_sdk/commands/common/errors.py
> +               f"or add the pack name to the ignored packs"
this option should not be exposed to the user.

2021-06-27 08:45 UTC, roysagi commented on demisto_sdk/commands/common/hook_validations/incident_field.py
> +        name_prefixes = pack_metadata.get('itemPrefix', [])
```suggestion
        name_prefixes = pack_metadata.get('itemPrefix', []) if pack_metadata.get('itemPrefix') else [pack_name]
```

2021-06-27 08:45 UTC, roysagi commented on demisto_sdk/commands/common/hook_validations/incident_field.py
> +                    suggested_fix=Errors.suggest_fix_field_name(field_name, pack_name)):
Well done!

2021-06-27 08:45 UTC, roysagi commented on demisto_sdk/commands/common/hook_validations/incident_field.py
> +                    return True
```suggestion
                    return True
                    
```

2021-06-27 08:45 UTC, roysagi commented on demisto_sdk/commands/common/hook_validations/incident_field.py
> +    def is_valid_incident_field_name_prefix(self):
this function is not trivial - please add a docstring here.

2021-06-27 08:45 UTC, roysagi commented on demisto_sdk/commands/common/hook_validations/incident_field.py
> +                return False
```suggestion
                return False
                
```

2021-06-27 08:45 UTC, roysagi commented on demisto_sdk/commands/common/hook_validations/incident_field.py
> +            name_prefixes = [pack_name]
you can remove this and see above

2021-06-27 08:45 UTC, roysagi commented on demisto_sdk/commands/common/tests/incident_field_test.py
> +    def test_is_valid_name_prefix(self, current_file, pack_metadata, answer, mocker):
please add given-when-then docstring

2021-06-27 08:45 UTC, roysagi commented on demisto_sdk/commands/validate/validate_manager.py
> +            return all([incident_field_validator.is_valid_file(validate_rn=False, is_new_file=True, validate_all=self.validate_all),
`is_new_file = not is_modified` no?

2021-06-27 08:45 UTC, roysagi commented on demisto_sdk/commands/validate/validate_manager.py
> +            return incident_field_validator.is_valid_file(validate_rn=False, is_new_file=True, validate_all=self.validate_all)
same comment as above

2021-06-27 08:45 UTC, roysagi commented on demisto_sdk/commands/common/errors.py
> +               "Also make sure to update the field id and cliName accordingly." \
suggest how the cli should look as well please

2021-06-27 12:12 UTC, sabaghadar commented on demisto_sdk/commands/validate/validate_manager.py
> +            return all([incident_field_validator.is_valid_file(validate_rn=False, is_new_file=True, validate_all=self.validate_all),
right.

2021-06-29 07:41 UTC, roysagi approved these changes
Seems good - please add a changelog entry

2021-06-29 07:41 UTC, roysagi commented on demisto_sdk/commands/common/errors.py
> +                                                 'RM100', 'RM102', 'RM104', 'RM106',
revert this change please

2021-06-29 15:50 UTC, merged