Fixing id set duplicates check
demisto/demisto-sdk pull request #1374
Opened 2021-06-16 11:27 UTC by PA-Rweins

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Must have
- [ ] Tests
- [ ] Documentation

2021-06-23 09:04 UTC, roysagi requested changes
@PA-Rweins - please add a changelog?

2021-06-23 09:04 UTC, roysagi commented on demisto_sdk/__main__.py
> +    id_set_creator.create_id_set(fail_on_duplicates=True)
make this a flag

2021-06-23 14:55 UTC, PA-Rweins commented on demisto_sdk/__main__.py
> +    id_set_creator.create_id_set(fail_on_duplicates=True)
Changed to a flag

2021-06-23 15:29 UTC, roysagi approved these changes

2021-06-23 15:34 UTC, teizenman commented on CHANGELOG.md
> +* Added the `-fd` flag for the **create-id-set** command which will fail the command if duplicates are found.
```suggestion
* Added the `--fail-duplicates` flag for the **create-id-set** command which will fail the command if duplicates are found.
```

2021-06-23 15:34 UTC, teizenman commented on .circleci/config.yml
> +              CI_COMMIT_BRANCH="master" demisto-sdk create-id-set -o ./Tests/id_set.json -fd
```suggestion
              CI_COMMIT_BRANCH="master" demisto-sdk create-id-set -o ./Tests/id_set.json --fail-duplicates
```

2021-06-24 08:05 UTC, PA-Rweins commented on .circleci/config.yml
> +              CI_COMMIT_BRANCH="master" demisto-sdk create-id-set -o ./Tests/id_set.json -fd
Fixed

2021-06-24 08:05 UTC, PA-Rweins commented on CHANGELOG.md
> +* Added the `-fd` flag for the **create-id-set** command which will fail the command if duplicates are found.
Fixed

2021-06-24 08:09 UTC, teizenman approved these changes

2021-06-24 11:27 UTC, merged