Fix-Docker-Image-Update-Release-Notes-Bug
demisto/demisto-sdk pull request #1389
Opened 2021-06-21 16:58 UTC by tomneeman151293

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Must have
- [ ] Tests
- [ ] Documentation

2021-06-22 07:48 UTC, tomneeman151293 commented
New unit test failure
https://app.circleci.com/pipelines/github/demisto/demisto-sdk/10086/workflows/833d6f21-6ad2-485a-b21b-43d4aed28a6c/jobs/46629

2021-06-28 11:09 UTC, dantavori requested changes
looks good 👍🏽

2021-06-28 11:09 UTC, dantavori commented on demisto_sdk/commands/update_release_notes/update_rn.py
> +                            new_rn = ''.join(rn_parts) + new_rn_part
let's move this part to a separate method for readability

2021-06-29 12:51 UTC, dantavori approved these changes

2021-06-29 14:39 UTC, merged