Generic objects validation
demisto/demisto-sdk pull request #1455
Opened 2021-07-10 11:10 UTC by ShacharKidor

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/38703

## Description
Adding validations to the new Generic objects entities (ObjectModules, ObjectTypes, ObjectFields): 
* Create 3 new schemes: objecttype and objectfield which are based on incidenttype and incidentfield schemes, and
   objectmodule scheme. 
* Integrating the validation of the new objects in the flow of demisto-sdk validate.

## Must have
- [ ] Tests
- [ ] Documentation

2021-07-11 06:54 UTC, roysagi requested changes
@ShacharKidor - This looks good but please add tests.

@Itay4 - FYI - I think we should push this in order to push your example pack PR.

2021-07-11 06:58 UTC, Itay4 commented
> @ShacharKidor - This looks good but please add tests.
> 
> @Itay4 - FYI - I think we should push this in order to push your example pack PR.

ill test my pr with this branch

2021-07-11 16:51 UTC, roysagi requested changes
Let's add a changelog as well

2021-07-11 16:51 UTC, roysagi commented on demisto_sdk/commands/common/tools.py
> +                    if 'definitionId' in _dict and 'genericModuleId' in _dict:
We might not save the `genericModuleId` field on content repo. so let's remove this condition (same for incident types above)

2021-07-11 16:51 UTC, roysagi commented on demisto_sdk/commands/common/tools.py
> +                            return FileType.GENERIC_FIELD
let's move this before the recognition of Incident fields.
Let's check that the `definitionId` is not `incident` or `indicator` and if so this should be classified as Generic Field

2021-07-11 16:51 UTC, roysagi commented on demisto_sdk/commands/common/tools.py
> +                            return FileType.GENERIC_TYPE
Same comment as Generic field detection, this time along side incident types.

2021-07-11 16:51 UTC, roysagi commented on demisto_sdk/commands/common/tools.py
> +                        return FileType.GENERIC_MODULE
Move this above line 1103 (before field identification) - only modules will have views and definitions

2021-07-11 17:46 UTC, Itay4 commented
validation passes - https://app.circleci.com/pipelines/github/demisto/content/99603/workflows/fea3479d-a1cd-473b-8985-b9e7d3598eac/jobs/395819
note the following:
```
================= Running validation on changed pack unique files =================

Validating Packs/RBVM unique pack files

Running pack dependencies validation on RBVM

Couldn't find any items for pack 'RBVM'. Please make sure:
1 - The spelling is correct.
2 - The id_set.json file is up to date. Delete the file by running: `rm -rf Tests/id_set.json` and rerun the command.
No first level dependencies found
id set validations for: Packs/RBVM
```
@roysagi if im not wrong, this is expected

2021-07-12 17:13 UTC, roysagi approved these changes

2021-07-12 17:13 UTC, roysagi commented on demisto_sdk/commands/validate/validate_manager.py
> +        path_without_last_dir = file_path.rstrip(f'{dir_name}').rstrip('/')
might be wiser to use:
`str(os.path.dirname(path)).endswith(GENERIC_TYPES_DIR)`

This way you can support windows devs as well.

2021-07-12 17:13 UTC, roysagi commented on CHANGELOG.md
> +* Added scheme validations to the new Generic Objects.
```suggestion
* Added scheme validations for the new Generic Object Types, Fields, and Modules.
```

2021-07-12 18:50 UTC, merged