addidng failed test
demisto/demisto-sdk pull request #1537
Opened 2021-08-04 17:23 UTC by daryakoval

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/39922

## Description
Contributions and Docs link was re-added if they were already exsist.
## Must have
- [x] Tests
- [x] Documentation

2021-08-15 03:45 UTC, dantavori requested changes

2021-08-15 11:59 UTC, dantavori requested changes
almost there 💪🏽

2021-08-15 11:59 UTC, dantavori commented on demisto_sdk/commands/unify/tests/yml_unifier_test.py
> +        - integration which have README in the integration dir, with "View Integration Documentation" doc link
```suggestion
        - integration which have a detailed description with "View Integration Documentation" doc link
```

2021-08-15 11:59 UTC, dantavori commented on demisto_sdk/commands/unify/yml_unifier.py
> +    def get_integration_doc_link(self, unified_yml: Dict, detailed_description='') -> str:
tip: with your current implementation, you added non-trivial logic (and in particular a non-trivial argument) to the function. the best practice would be to keep the logic here as is, and when you **call** this function, check before if there is already a doc link in the current detailed description, and if not - call the function.

2021-08-16 06:47 UTC, dantavori approved these changes
looks great

2021-08-16 07:40 UTC, tomneeman151293 commented on CHANGELOG.md
> +* Fixed an issue when `(Partner Contridution)` was added twice to the display name during the download and re-upload.
```suggestion
* Fixed an issue when `(Partner Contribution)` was added twice to the display name during the download and re-upload.
```

2021-08-16 09:12 UTC, merged