Update get_ignore_pack_skipped_tests to support tpb from different packs
demisto/demisto-sdk pull request #1599
Opened 2021-08-28 19:16 UTC by Shellyber

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Must have
- [ ] Tests
- [ ] Documentation
- [ ] [VS Code Extension](https://docs.gitlab.com/ee/ci/yaml/#tags)
  - [ ] Functionality implemented in the extension - <u>\<link-to-pr-here\></u>
  - [ ] N/A - Functionality cannot be implemented in the extension because <u>\<add-reason-here\></u>

2021-08-29 13:04 UTC, Itay4 commented on demisto_sdk/commands/common/tools.py
> +def get_ignore_pack_skipped_tests(pack_name: str, modified_packs) -> set:
```suggestion
def get_ignore_pack_skipped_tests(pack_name: str, modified_packs: set) -> set:
```

2021-08-29 13:04 UTC, Itay4 commented on demisto_sdk/commands/common/tests/tools_test.py
> +    ignore_test_set = get_ignore_pack_skipped_tests(fake_pack_name, {fake_pack_name})
please update test docstring according to these changes

2021-09-02 14:35 UTC, yaakovi requested changes

2021-09-02 14:35 UTC, yaakovi commented on demisto_sdk/commands/common/tools.py
> +        test_playbook_name = list(test_playbook_dict.keys())[0]
```suggestion
        test_playbook_id = list(test_playbook_dict.keys())[0]
```

2021-09-02 14:35 UTC, yaakovi commented on demisto_sdk/commands/common/tools.py
> +            return test_playbook_name, test_playbook_pack
```suggestion
            return test_playbook_id, test_playbook_pack
```

2021-09-02 14:35 UTC, yaakovi commented on demisto_sdk/commands/common/tools.py
> +                    ignored_tests_set.add(test_id)
why is that inside the previous loop?

2021-09-02 19:45 UTC, yaakovi approved these changes
please fix the LGTM warning

2021-09-05 09:01 UTC, merged