Validate api key parameter has credentials type
demisto/demisto-sdk pull request #1680
Opened 2021-10-21 09:38 UTC by MosheEichler

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/42267

## Description
add a validation to verify API token is in credential type (9) and not in encrypted type (4)
For more info see https://xsoar.pan.dev/docs/integrations/yaml-file#configuration

## Screenshots
![Screen Shot 2021-10-21 at 12 37 24](https://user-images.githubusercontent.com/78307768/138252003-7bb9fb3d-2434-49fb-8dd0-104600b9879f.png)

2021-10-21 09:56 UTC, amshamah419 commented on CHANGELOG.md
> +* Added a validation to verify **API token** parameter in integration configuration is in credential type.
```suggestion
* Added a validation to verify that the**API token** parameter for an integration configuration is a known credential type.
```

2021-10-21 16:15 UTC, ShahafBenYakir commented on demisto_sdk/commands/common/errors.py
> +        return f'The type field of the {param_name} parameter should be 9'
```suggestion
        return f'In order to allow fetching the {param_name} from an external vault, the type of the {param_name} parameter should be changed from 'Encrypted' (type 4), to 'Credentials' (type 9)'. For more details check the convention for credentials - https://xsoar.pan.dev/docs/integrations/code-conventions#credentials
```

2021-11-07 09:28 UTC, reutshal requested changes
Nice, please see my comments

2021-11-07 09:28 UTC, reutshal commented on CHANGELOG.md
> +* Added a validation to verify **API token** parameter in integration configuration is in credential type.
Please except the changes

2021-11-07 09:28 UTC, reutshal commented on demisto_sdk/commands/common/hook_validations/integration.py
> +                conf_json_data (dict):
Please add a description

2021-11-09 13:18 UTC, reutshal commented on demisto_sdk/commands/common/hook_validations/integration.py
> +                conf_json_data (dict) The conf.json file data:
```suggestion
                conf_json_data (dict): The conf.json file data.
```

2021-11-09 13:29 UTC, reutshal commented on CHANGELOG.md
> +* Added a validation to ensure that the type for **API token** (and similar) parameters are configured correctly as a `credential` type in the integration configuration YML
```suggestion
* Added a validation to ensure that the type for **API token** (and similar) parameters are configured correctly as a `credential` type in the integration configuration YML.
```

2021-11-10 08:27 UTC, reutshal approved these changes

2021-11-11 09:06 UTC, ShahafBenYakir approved these changes

2021-11-11 09:44 UTC, merged