Validate unsearchable
demisto/demisto-sdk pull request #1697
Opened 2021-11-07 16:42 UTC by yucohen

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Must have
- [ ] Tests
- [ ] Documentation
- [ ] [VS Code Extension](https://docs.gitlab.com/ee/ci/yaml/#tags)
  - [ ] Functionality implemented in the extension - <u>\<link-to-pr-here\></u>
  - [ ] N/A - Functionality cannot be implemented in the extension because <u>\<add-reason-here\></u>

2021-11-11 09:57 UTC, reutshal requested changes
Looks good, please see my comments

2021-11-11 09:57 UTC, reutshal commented on demisto_sdk/commands/common/hook_validations/generic_field.py
> +            bool. Whether the file's unsearchable field is se to true.
```suggestion
            bool. Whether the file's unsearchable key is set to true.
```

2021-11-11 09:57 UTC, reutshal commented on demisto_sdk/commands/common/hook_validations/incident_field.py
> +            bool. Whether the file's unsearchable field is se to true.
remember to change to "key"

2021-11-11 09:57 UTC, reutshal commented on demisto_sdk/commands/validate/tests/validators_test.py
> +    @pytest.mark.parametrize('answer, unsearchable, validator', [(True, True, IncidentFieldValidator),
```suggestion
    @pytest.mark.parametrize('expected_result, unsearchable, validator', [(True, True, IncidentFieldValidator),
```

I think this name is better for your test

2021-11-11 09:57 UTC, reutshal commented on demisto_sdk/tests/test_files/validate_integration_test_valid_types.py
> +    "unsearchable": True,
Some of the values are lowercased and some uppercased. Is there a reason?
If not, please let's be consistent.

2021-11-11 12:15 UTC, reutshal commented on demisto_sdk/commands/common/errors.py
> +        return 'The unsearchable key in indicator and incident field should be set to true.'
```suggestion
        return 'The unsearchable key in indicator and incident fields should be set to true.'
```

2021-11-11 12:28 UTC, reutshal requested changes

2021-11-11 12:28 UTC, reutshal commented on demisto_sdk/commands/common/errors.py
> +        return 'The unsearchable key in generic field should be set to true.'
```suggestion
        return 'The unsearchable key in a generic field should be set to true.'
```

2021-11-11 12:28 UTC, reutshal commented on CHANGELOG.md
> +* Added a validation to the **validate** command that verifies that `unsearchable` field in incident, indicator and generic fields is set to true.
```suggestion
* Added validation to the **validate** command that verifies the `unsearchable` key in incident, indicator and generic fields is set to true.
```

2021-11-11 12:28 UTC, reutshal commented on demisto_sdk/commands/common/errors.py
> +    'IN109', 'IN110', 'IN122', 'IN126', 'IN128', 'IN135', 'IN136', 'IN139', 'IN144',
Why was this line added?

2021-11-11 12:28 UTC, reutshal commented on demisto_sdk/commands/validate/tests/validators_test.py
> +    def test_is_valid_unsearchable_key_if(self, pack: Pack, expected_result, unsearchable):
```suggestion
    def test_is_valid_unsearchable_key_incident_field(self, pack: Pack, expected_result, unsearchable):
```

2021-11-11 12:28 UTC, reutshal commented on demisto_sdk/commands/validate/tests/validators_test.py
> +    def test_is_valid_unsearchable_key_gf(self, pack: Pack, expected_result, unsearchable):
```suggestion
    def test_is_valid_unsearchable_key_generic_field(self, pack: Pack, expected_result, unsearchable):
```

2021-11-11 12:38 UTC, yucohen commented on demisto_sdk/commands/common/errors.py
> +    'IN109', 'IN110', 'IN122', 'IN126', 'IN128', 'IN135', 'IN136', 'IN139', 'IN144',
merge conflicts 🤦🏼‍♀️

2021-11-11 14:03 UTC, reutshal approved these changes

2021-11-11 21:11 UTC, tomneeman151293 requested changes
Nice. Please also add the following scenarios to is_valid_file  test for both generic field and indicator field
1. added_file is False, unsearchable is False
2. added_file is False, unsearchable is True
3. added_file is True, unsearchable is False
4. added_file is True, unsearchable is True

2021-11-11 21:11 UTC, tomneeman151293 commented on demisto_sdk/commands/common/hook_validations/generic_field.py
> +        indicator_field_unsearchable = self.current_file.get('unsearchable', True)
```suggestion
        generic_field_unsearchable = self.current_file.get('unsearchable', True)
```

2021-11-11 21:11 UTC, tomneeman151293 commented on demisto_sdk/commands/common/hook_validations/generic_field.py
> +        if indicator_field_unsearchable:
```suggestion
        if generic_field_unsearchable:
```

2021-11-11 21:11 UTC, tomneeman151293 commented on demisto_sdk/commands/validate/validate_manager.py
> +                        incident_field_validator.is_valid_unsearchable_key()])
why is this needed here? shouldn't it already be executed in is_valid_file?

2021-11-14 08:46 UTC, tomneeman151293 commented
Also - need to make sure running format on an incident/indicator field changes this field to true (and add relevant tests for it)

2021-11-16 06:59 UTC, tomneeman151293 requested changes
Very nice! One last small note tho

There is no need to add a specific function just for unsearchable.
Please see `ARGUMENTS_DEFAULT_VALUES` in fromat_constants.
I think adding a pair of
'unsearchable': (True, ['IncidentFieldJSONFormat', 'IndicatorFieldJSONFormat', 'GenericFieldJSONFormat'])
Will make the format change unsearchable to true without the needing of unsearchable func, see `set_default_values_as_needed` in update_generic_json.py.
 so you won't need to modify any format/update_incident/generic/indicator field.py files.

Also - I might have missed but did you add tests to the format changes?

2021-11-16 06:59 UTC, tomneeman151293 commented on demisto_sdk/commands/format/update_generic.py
> +        self.data['unsearchable'] = UNSEARCHABLE_KEY_DEFAULT_VALUE
Not needed after the requested change is done

2021-11-16 06:59 UTC, tomneeman151293 commented on demisto_sdk/commands/format/update_genericfield.py
> +            self.update_unsearchable_key()
Not needed after the requested change is done

2021-11-16 06:59 UTC, tomneeman151293 commented on demisto_sdk/commands/format/update_incidentfields.py
> +            self.update_unsearchable_key()
Not needed after the requested change is done

2021-11-16 06:59 UTC, tomneeman151293 commented on demisto_sdk/commands/format/update_indicatorfields.py
> +            self.update_unsearchable_key()
Not needed after the requested change is done

2021-11-16 06:59 UTC, tomneeman151293 commented on demisto_sdk/commands/format/format_constants.py
> +UNSEARCHABLE_KEY_DEFAULT_VALUE = True
Can remove this

2021-11-16 06:59 UTC, tomneeman151293 commented on demisto_sdk/commands/common/hook_validations/generic_field.py
> +        if self.handle_error(error_message, error_code, file_path=self.file_path):
```suggestion
        if self.handle_error(error_message, error_code, file_path=self.file_path, suggested_fix=Errors.suggest_fix(self.file_path)):
```

2021-11-16 06:59 UTC, tomneeman151293 commented on demisto_sdk/commands/common/hook_validations/incident_field.py
> +        if self.handle_error(error_message, error_code, file_path=self.file_path):
```suggestion
        if self.handle_error(error_message, error_code, file_path=self.file_path, suggested_fix=Errors.suggest_fix(self.file_path)):
```

2021-11-16 11:50 UTC, tomneeman151293 approved these changes
Great Work!

2021-11-16 11:51 UTC, tomneeman151293 commented
Please re-trigger run after this PR is merged
https://github.com/demisto/content/pull/15798
it will fix your validate files failure (which isn't related to you)

2021-11-16 14:22 UTC, merged