Enhancements for generate-docs
demisto/demisto-sdk pull request #1732
Opened 2021-12-01 15:01 UTC by ilaner

## Status
- [x] In Progress

## Related Issues
fixes: https://github.com/demisto/etc/issues/44063

## Description
Added the following changes:

1. Supports giving filepath and comma-seperated list as command examples to `generate-docs` to scripts and integrations
2. Support for giving more than one example to same command or script

## Screenshots
Paste here any images that will help the reviewer

## Must have
- [ ] Tests
- [ ] Documentation

2021-12-08 12:48 UTC, DeanArbel requested changes

2021-12-08 12:48 UTC, DeanArbel commented on demisto_sdk/commands/generate_docs/generate_integration_doc.py
> +            '```{}```'.format(cmd_from_yaml['name']),
are you sure this part is needed? I don't see it in the previous implementation.
Please show me offline an example output.

2021-12-08 12:48 UTC, DeanArbel commented on demisto_sdk/tests/test_files/integration-display-credentials-none/README.md
> +Use the IPinfo.io API to get data about an IP address.
What is this?

2021-12-08 13:31 UTC, ilaner commented on demisto_sdk/tests/test_files/integration-display-credentials-none/README.md
> +Use the IPinfo.io API to get data about an IP address.
have no idea deleted it

2021-12-13 11:35 UTC, DeanArbel approved these changes
@ilaner Please look at the validations.

2021-12-14 13:04 UTC, DeanArbel commented on demisto_sdk/commands/generate_docs/README.md
> +If the file or list containing a command with more than one example for it, all of them will be used.
```suggestion
- Path for file containing examples. Each command should be in a separate line. or a comma seperated list of commands
- Comma separated list of examples, wrapped by quotes.
If the file or list contains a command with more than one example, all of them will be used.
```

2021-12-14 14:20 UTC, merged