SDK run-test-playbook Command
demisto/demisto-sdk pull request #1738
Opened 2021-12-05 20:05 UTC by ChanochShayner

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/40820

## Description
Added a new SDK command `run-test-playbook`.

## Must have
- [x] Tests
- [x] Documentation

2021-12-15 17:00 UTC, guykeller requested changes

2021-12-16 06:57 UTC, ChanochShayner commented on demisto_sdk/commands/run_test_playbook/test_playbook_runner.py
> +        Run all pack test playbooks
done

2021-12-16 06:57 UTC, ChanochShayner commented on demisto_sdk/commands/run_test_playbook/test_playbook_runner.py
> +        valid = True
done

2021-12-16 06:57 UTC, ChanochShayner commented on demisto_sdk/commands/run_test_playbook/test_playbook_runner.py
> +                print_color("Error: Missing option '-tpb' / '--test-playbook-path'.", LOG_COLORS.RED)
done

2021-12-16 06:58 UTC, ChanochShayner commented on demisto_sdk/commands/run_test_playbook/test_playbook_runner.py
> +            all_tpb_files_list.extend(self.run_all_test_playbooks())
done

2021-12-16 06:58 UTC, ChanochShayner commented on demisto_sdk/commands/run_test_playbook/test_playbook_runner.py
> +        all_tpb_files_list: list = []
done

2021-12-16 07:01 UTC, ChanochShayner commented on demisto_sdk/commands/run_test_playbook/test_playbook_runner.py
> +    def run_test_playbooks(self) -> int:
done

2021-12-16 07:09 UTC, ChanochShayner commented on demisto_sdk/commands/run_test_playbook/test_playbook_runner.py
> +            all_tpb_files_list.append(self.test_playbook_path)
done

2021-12-16 07:28 UTC, ChanochShayner commented on demisto_sdk/commands/run_test_playbook/test_playbook_runner.py
> +    def run_test_playbook_by_id(self, test_playbook_id):
done

2021-12-16 07:28 UTC, ChanochShayner commented on demisto_sdk/commands/run_test_playbook/test_playbook_runner.py
> +            all_tpb_files_list.append(self.test_playbook_path)
done

2021-12-16 07:29 UTC, ChanochShayner commented on demisto_sdk/commands/run_test_playbook/test_playbook_runner.py
> +    def run_test_playbooks(self) -> int:
removed

2021-12-19 07:44 UTC, guykeller approved these changes

2021-12-19 09:17 UTC, merged