Postman request
demisto/demisto-sdk pull request #1739
Opened 2021-12-06 10:39 UTC by BEAdi

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/44189

## Description
Request data will have the python argument name and not the raw data argument name.

2021-12-06 10:59 UTC, BEAdi commented
failing test before fixing: https://app.circleci.com/pipelines/github/demisto/demisto-sdk/12833/workflows/76445879-86ca-4a44-af82-19cca5af0fc5/jobs/68709

2021-12-07 14:31 UTC, PA-Rweins requested changes

2021-12-07 14:31 UTC, PA-Rweins commented on demisto_sdk/commands/postman_codegen/postman_codegen.py
> +                        if arg.in_object == list(path) and k in arg.name:
Why `k in arg.name` and not just check the suffix?

2021-12-22 09:34 UTC, BEAdi commented on demisto_sdk/commands/postman_codegen/tests/postman_codegen_test.py
> +        request_body = {
Done

2021-12-22 09:34 UTC, BEAdi commented on demisto_sdk/commands/postman_codegen/tests/postman_codegen_test.py
> +        request_body = {
Done

2021-12-22 09:34 UTC, BEAdi commented on demisto_sdk/commands/postman_codegen/tests/postman_codegen_test.py
> +            "key1": "val1",
Done

2021-12-22 16:14 UTC, PA-Rweins approved these changes
LGTM

2021-12-22 16:14 UTC, PA-Rweins approved these changes
LGTM

2021-12-23 08:28 UTC, merged