Validate yml
demisto/demisto-sdk pull request #1769
Opened 2021-12-27 11:14 UTC by bziser

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: [link to the issue](https://github.com/demisto/etc/issues/43453)

## Description
Added ryaml.load in yml validation

## Screenshots
Paste here any images that will help the reviewer

## Must have
- [ ] Tests
- [ ] Documentation
- [ ] [VS Code Extension](https://docs.gitlab.com/ee/ci/yaml/#tags)
  - [ ] Functionality implemented in the extension - <u>\<link-to-pr-here\></u>
  - [ ] N/A - Functionality cannot be implemented in the extension because <u>\<add-reason-here\></u>

2021-12-27 16:42 UTC, yuvalbenshalom requested changes
please add tests and add to the PR a snippet of the error it prints.

2021-12-28 11:25 UTC, yuvalbenshalom requested changes
looks good. just add standard test doc string.

2021-12-28 11:25 UTC, yuvalbenshalom commented on demisto_sdk/commands/common/tests/structure_test.py
> +    def test_invalid_yml(self, capsys):
please add standard test doc string.

2021-12-28 11:25 UTC, yuvalbenshalom commented
@dorschw FYI

2021-12-28 11:36 UTC, dorschw approved these changes

2021-12-28 13:01 UTC, yuvalbenshalom approved these changes

2021-12-28 13:11 UTC, merged