Starting over
demisto/demisto-sdk pull request #1786
Opened 2022-01-02 10:02 UTC by MLainer1

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
Adding validation for deleted integrations files.

## Must have
- [ ] Tests
- [ ] Documentation
- [ ] [VS Code Extension](https://docs.gitlab.com/ee/ci/yaml/#tags)
  - [ ] Functionality implemented in the extension - <u>\<link-to-pr-here\></u>
  - [ ] N/A - Functionality cannot be implemented in the extension because <u>\<add-reason-here\></u>

2022-01-03 09:01 UTC, tomneeman151293 requested changes
Awesome! Important note:
1) Some files can! ben deleted
- Test PBs
- Maybe more files
I suggest making a test for each type of content entity, and see that for each content entity, the validate on deleted files returns True/False if it can or cannot be deleted.

The issue itself talked only about integrations/scripts but I think we should expand it.
- add a NOT_ALLOWED_DELETE_FILETYPES of file types who cannot be deleted
- Only return error for every file whom file type is in NOT_ALLOWED_DELETE_FILETYPES
Also
- You should add a test for every deleted file if its file type is in NOT_ALLOWED_DELETE_FILETYPES

2022-01-30 13:53 UTC, dorschw commented
@MLainer1 what's our status on this?

2022-01-30 14:51 UTC, idovandijk commented
Can you please add what this validation does?

2022-03-08 15:54 UTC, idovandijk commented
@MLainer1 I'm not 100% certain about the logic for Git determining that a file is deleted. I do think that it has false-positives.
For example: playbooks goes through a major rework (lots of tasks renamed, moved, replaced), or a large enhancement to a playbook which can introduce a very different readme file.
OR - when a playbook is renamed in favor of a new playbook which replaces the old file name.
For example: `Phishing.yml` becomes `Phishing_6_0.yml` and then a new playbook takes the name of `Phishing.yml`. This happens from time to time and we don't want to have to force merge those

2022-03-09 09:52 UTC, dantavori requested changes
also make the change to address the edge case where git recognizes renamed files as deleted+added

2022-03-09 09:52 UTC, dantavori commented on demisto_sdk/commands/validate/validate_manager.py
> +        return file_type not in file_types_not_allowed_to_be_deleted
more simple:
```suggestion
        file_type = find_type(file_path)
        return file_type in FileType_ALLOWED_TO_DELETE or not file_type
```

2022-03-09 09:52 UTC, dantavori commented on demisto_sdk/tests/integration_tests/validate_integration_test.py
> +        mocker.patch.object(ValidateManager, 'validate_deleted_files', return_value=True)
probably don't need this mock

2022-03-09 10:20 UTC, dorschw commented on CHANGELOG.md
> +* Added to **validate** a validation that prevents the user to delete importent files.
```suggestion
* Added a **validate** check to prevent deletion of files whose deletion is not supported by the XSOAR marketplace.
```

2022-03-13 08:56 UTC, dantavori approved these changes

2022-03-13 11:16 UTC, merged