improve image tests
demisto/demisto-sdk pull request #1848
Opened 2022-01-27 16:53 UTC by dorschw

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/46177

## Description
A few sentences describing the overall goals of the pull request's commits.

## Must have
- [x] Tests

2022-01-27 17:44 UTC, DeanArbel approved these changes
Impressive changes. Well done.

2022-01-30 07:50 UTC, tkatzir requested changes
Great work!
Missing an extra space at the end, for readability.

2022-01-30 07:50 UTC, tkatzir commented on demisto_sdk/commands/common/errors.py
> +            error += f'got HTTP response code {http_code}'
Need to add an extra space at the end?

2022-01-30 07:50 UTC, tkatzir commented on demisto_sdk/commands/common/errors.py
> +    def invalid_readme_image_error(path: str, error_type: str, http_code: Optional[int] = None):
Accept the `reason` param as well

2022-01-30 07:50 UTC, tkatzir commented on demisto_sdk/commands/common/errors.py
> +            error += f'got HTTP response code {http_code}'
Print the `reason` param as well

2022-01-30 09:27 UTC, idovandijk commented
@dorschw can u please explain to me in short what this change is?

2022-01-30 10:31 UTC, dorschw commented
> @dorschw can u please explain to me in short what this change is?

Updated PR description:
```
## Description
- Added a retry mechanism to the validation that checks remote images.
- Only checking for http status code without downloading the image checked (thanks @ilaner for the idea)
```

2022-01-30 12:13 UTC, idovandijk approved these changes
So nothing for me to review here, if they approved it's fine

2022-01-30 13:00 UTC, tkatzir approved these changes

2022-01-30 13:01 UTC, merged