Auto generate YML from python initial design
demisto/demisto-sdk pull request #1888
Opened 2022-02-14 15:17 UTC by DinaMeylakh

**WARNING** The following files are only for the design and they should not be merged to master.

### Design
#### How
**DetailsCollecto**r: The class that will hold the wrappers that collect details on functions that are wrapped with them. 
**Python script with functions**: The file which initializes the DetailsCollector and uses its' wrappers, providing details explicitly and implicitly.
**YMLGenerator**: The class which is called when generating the yml. It obtains the relevant DetailsCollector and the functions using it from the python path. It then makes the DetailsCollector collect the details and writes yml file accordingly.

The following files serve as a POC and a way to document the heart of the design.

#### Where
The logic will sit inside `demisto_sdk/commands/unify` and will be called whenever unify is being called, creating the yml file only when needed. Not as part of the source code.

Running the files results in:
![Screen Shot 2022-02-14 at 17 06 15](https://user-images.githubusercontent.com/72339665/153889498-87ce9d54-a2d1-4640-bcb9-765e59e9b25e.png)

2022-02-15 08:29 UTC, Itay4 reviewed
overall looks good, i think we can improve the naming

2022-02-20 13:58 UTC, tkatzir requested changes
Looks good!

2022-02-20 13:58 UTC, tkatzir commented on demisto_sdk/commands/generate_yml/yml_metadata_collector.py
> +    def add_command(self, command_name=None):
I would simply call it "command"
It's a decorator for a command.

2022-02-20 13:58 UTC, tkatzir commented on demisto_sdk/commands/generate_yml/yml_metadata_collector.py
> +        def add_command_wrapper(func):
Similarly - "command_wrapper"

2022-03-29 13:09 UTC, closed without merging