lint changes
demisto/demisto-sdk pull request #1946
Opened 2022-03-14 14:11 UTC by esharf

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Description
A few sentences describing the overall goals of the pull request's commits.

## Must have
- [ ] Tests

2022-03-14 20:57 UTC, dorschw requested changes

2022-03-15 08:09 UTC, dorschw requested changes

2022-03-15 08:09 UTC, dorschw commented on demisto_sdk/commands/lint/docker_helper.py
> +            a list of mounts
please explain what this method does (its name suggests it copies files. from where to where? and if so, what `mounts` are returned?)

2022-03-15 08:09 UTC, dorschw commented on demisto_sdk/commands/lint/docker_helper.py
> +        this function is used to create a new image of devtestsdemisto docker images.
please explain the flow here.

2022-03-15 08:27 UTC, dorschw commented on demisto_sdk/commands/lint/docker_helper.py
> +            3. commit the docker changes (e.g. new python package installed) to a new image
```suggestion
            1. creating a container using an existing image
            2. running the istallation scripts 
            3. committing the docker changes (installed packages) to a new local image
```

2022-03-15 08:29 UTC, dorschw commented
Please edit the PR description, explaining what it is about for future devs.

2022-03-15 13:00 UTC, yaakovi approved these changes

2022-03-15 13:33 UTC, merged