dev task - Adding a new flag to *validate* to run specific validations
demisto/demisto-sdk pull request #1966
Opened 2022-03-20 07:51 UTC by MLainer1

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/47233

## Description
Adding a new flag to *validate* to run specific validations using decorators
## Screenshots
Paste here any images that will help the reviewer

## Must have
- [ ] Tests
- [ ] Documentation
- [ ] [VS Code Extension](https://docs.gitlab.com/ee/ci/yaml/#tags)
  - [ ] Functionality implemented in the extension - <u>\<link-to-pr-here\></u>
  - [ ] N/A - Functionality cannot be implemented in the extension because <u>\<add-reason-here\></u>

2022-03-30 14:29 UTC, dantavori requested changes

2022-03-30 14:29 UTC, dantavori commented on .gitignore
> +.vscode/*
remove

2022-04-06 15:21 UTC, idovandijk reviewed
@MLainer1 if I understood correctly the normal `validate` command remains the same right? We're just adding the ability to also run specific validations if needed

2022-04-11 12:08 UTC, dantavori requested changes
exhausting 😓
but great job.
please open an issue for phase 2: create a test for validate which checks that every validation function has a decorator.

2022-04-11 12:08 UTC, dantavori commented on demisto_sdk/commands/common/hook_validations/xsoar_config_json.py
> +                         suppress_print=suppress_print, json_file_path=json_file_path, specific_validations=specific_validations)
please add missing decorator in `load_xsoar_configuration_file()`

2022-04-12 11:36 UTC, MLainer1 commented on demisto_sdk/commands/common/hook_validations/pack_unique_files.py
> +                         suppress_print=suppress_print, json_file_path=json_file_path, specific_validations=specific_validations)
This command is critical for other functions in validate, so we need to run it everytime

2022-04-14 17:12 UTC, dantavori approved these changes
Happy Passover!
Let's do some last tests next week before you merge

2022-04-14 17:12 UTC, dantavori commented on demisto_sdk/commands/validate/validate_manager.py
> +    def validate_release_notes_for_new_pack(self, pack_name, file_path):
```suggestion
    def validate_no_release_notes_in_new_pack(self, pack_name, file_path):
```

2022-04-25 14:18 UTC, dantavori commented on demisto_sdk/commands/common/hook_validations/integration.py
> +            Returns True if valid, and False otherwise.
please change this method's name to `is_valid_display_configuration`

2022-04-25 14:22 UTC, dantavori commented on demisto_sdk/commands/common/hook_validations/integration.py
> +                is_removed_parameter = False
same here, make sure your method & variable names are correct (should be something like `no_removed_integration_parameters_exist` and `no_removed_parameters`)

2022-04-25 14:23 UTC, dantavori commented on demisto_sdk/commands/common/hook_validations/integration.py
> +            bool. True if valid, and False otherwise.
is_changed_context_path -> no_change_to_context_path

2022-05-01 12:03 UTC, merged