Add Wizard Content Item
demisto/demisto-sdk pull request #2031
Opened 2022-04-14 07:10 UTC by DeanArbel

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/47460

## Description
Add wizard content item support.

## Must have
- [ ] Tests
- [ ] Documentation
- [ ] [VS Code Extension](https://docs.gitlab.com/ee/ci/yaml/#tags)
  - [ ] Functionality implemented in the extension - <u>\<link-to-pr-here\></u>
  - [ ] N/A - Functionality cannot be implemented in the extension because <u>\<add-reason-here\></u>

2022-05-01 13:01 UTC, tkatzir requested changes
Looks very good!
Please add The validation we discussed:
That the `integration` and `playbooks` that are referenced in the wizard actually appear in the `dependency packs`.

2022-05-02 07:50 UTC, DeanArbel commented on demisto_sdk/commands/create_artifacts/content_artifacts_creator.py
> +            ContentItems.WIZARD: [],
Originally I made it `WIZARD` but I'll change it to `WIZARDS`.

2022-05-02 07:53 UTC, DeanArbel commented on demisto_sdk/commands/create_artifacts/tests/data/id_set_alrenative_fields.json
> +    "Wizards": []
@tkatzir that's not possible since this a `json` file.
https://stackoverflow.com/a/201856

2022-05-02 07:53 UTC, DeanArbel commented on demisto_sdk/commands/common/update_id_set.py
> +        a list of Job data.
Oops :)

2022-05-02 07:56 UTC, DeanArbel commented on demisto_sdk/commands/common/hook_validations/wizard.py
> +    def is_valid_version(self):
It's already there - I'm just skipping it, as this check is not really required for newer items.

2022-05-02 08:14 UTC, DeanArbel commented on demisto_sdk/commands/common/constants.py
> +    'Wizard',
Wizards

2022-05-02 08:31 UTC, DeanArbel commented on demisto_sdk/commands/common/constants.py
> +    FileType.WIZARD: 'Wizard',
I don't think we'll ever have more than 1 `wizard` in a pack, unlike any of the other types.

2022-05-03 06:48 UTC, tkatzir commented on demisto_sdk/commands/common/hook_validations/wizard.py
> +    def is_valid_version(self):
So if we remove it, it'll use the parent's code, wouldn't it?

2022-05-03 06:54 UTC, tkatzir approved these changes
Great job, and we could use it as an example for future similar features. :-)

2022-05-03 08:09 UTC, dorschw commented on TestSuite/repo.py
> +        wizard.update({'wizard': {}})
can we put all in write_json instead of calling update twice?

2022-05-03 08:10 UTC, dorschw commented on demisto_sdk/commands/common/constants.py
> +    WIZARDS_DIR
```suggestion
    WIZARDS_DIR,
```

2022-05-03 08:14 UTC, dorschw commented on demisto_sdk/commands/common/tools.py
> +        if isinstance(_dict, dict) and 'wizard' in _dict.keys():
```suggestion
        if isinstance(_dict, dict) and 'wizard' in _dict:
```

2022-05-03 08:15 UTC, dorschw approved these changes
very nice

2022-05-03 11:59 UTC, DeanArbel commented on demisto_sdk/commands/common/hook_validations/wizard.py
> +    def is_valid_version(self):
exactly

2022-05-03 16:37 UTC, merged