Added error for case that cliName and id do not matches
demisto/demisto-sdk pull request #2059
Opened 2022-04-26 13:29 UTC by israelpoli

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Description
Added error for case that cliName and id do not matches, and added to the ALLOWED_IGNORE_ERRORS list.

## Must have
- [x] Tests

2022-04-26 16:33 UTC, dorschw commented on demisto_sdk/commands/common/errors.py
> +               f'Please change cliName to {cli_name_correct} (the flat-case version of id)'
```suggestion
               f'Please change cliName to {cli_name_correct} (the flat-case version of id, excluding item-type prefixes)'
```

2022-04-26 16:34 UTC, dorschw requested changes

2022-04-27 06:35 UTC, israelpoli commented on demisto_sdk/commands/common/errors.py
> +    'BA101', 'BA106', 'BA108', 'BA109', 'BA110', 'BA111', 'BA112', 'BA113', 'BA116',
Yes, to avoid failure of existing files

2022-04-27 06:52 UTC, israelpoli commented on demisto_sdk/commands/validate/tests/validators_test.py
> +                "BA110", 'BA111', "BA112", "BA113", "BA114", "BA115", "BA116", "BC101", "BC102", "BC103", "BC104"}.issubset(set(error_list))
`{}.issubset(<set>)`

2022-04-27 14:57 UTC, dorschw commented on demisto_sdk/commands/validate/tests/validators_test.py
> +                "BA110", 'BA111', "BA112", "BA113", "BA114", "BA115", "BA116", "BC101", "BC102", "BC103", "BC104"}.issubset(set(error_list))
`{}.issubset(iterable)` 🙃 

[example](https://onlinegdb.com/FWe3sXQfpT)

2022-04-27 15:07 UTC, dorschw approved these changes

2022-04-28 07:51 UTC, merged