failed unit-test
demisto/demisto-sdk pull request #2183
Opened 2022-06-19 17:10 UTC by GuyAfik

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the [issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-3227)

## Description
A few sentences describing the overall goals of the pull request's commits.

## Must have
- [x] Tests

2022-06-19 17:22 UTC, GuyAfik commented
failed unit-test - https://app.circleci.com/pipelines/github/demisto/demisto-sdk/16975/workflows/81d70075-809b-4f75-8050-e2e6801ec517/jobs/108248

2022-06-19 17:37 UTC, GuyAfik commented
failed unit-test - https://app.circleci.com/pipelines/github/demisto/demisto-sdk/16976/workflows/ce745594-6878-4f1a-9cc0-2fadafb3f525/jobs/108253

2022-06-20 07:57 UTC, GuyAfik commented
@JudahSchwartz i guess we can shorten the ```CHANGELOG.md``` here to a more concise string, let me know if you have got something better

2022-06-20 11:12 UTC, JudahSchwartz requested changes

2022-06-20 11:12 UTC, JudahSchwartz commented on demisto_sdk/commands/common/hook_validations/id.py
>      def is_entity_version_match_playbook_version(self, implemented_entity_list_from_playbook,
there are some logic issues here as discussed in person,
lets refactor this method. Broadly - group entities by id so we will have have a list of versions by id, and only compare to the min version

2022-06-21 05:34 UTC, dorschw reviewed
Nice

2022-06-21 05:34 UTC, dorschw commented on demisto_sdk/commands/common/hook_validations/id.py
> +                if tasks_data and LooseVersion(main_playbook_version) >= LooseVersion('6.0.0') else False
Please use `packaging.version.Version` instead of `LooseVersion`

2022-06-21 05:34 UTC, dorschw commented on demisto_sdk/commands/common/hook_validations/id.py
> +            return LooseVersion(min_version_entity.get('fromversion')) <= LooseVersion(main_playbook_version)
here too

2022-06-21 05:34 UTC, dorschw commented on demisto_sdk/commands/common/hook_validations/id.py
> +            entity_id = list(entity.keys())[0]
```suggestion
            entity_id = next(entity.keys())
```

2022-06-21 06:48 UTC, GuyAfik commented on demisto_sdk/commands/common/hook_validations/id.py
> +            entity_id = list(entity.keys())[0]
```TypeError: 'dict_keys' object is not an iterator```

2022-06-21 08:12 UTC, dorschw approved these changes
Works for me, please wait for @JudahSchwartz to CR this too.

2022-06-21 08:20 UTC, idovandijk commented
@GuyAfik are we sure that the invalid fromversion is in the subplaybooks and not the main playbook? Also what is the issue with the loops? Can you please let me know before you merge since this PR seems to affect playbooks

2022-06-21 08:49 UTC, GuyAfik commented
> @GuyAfik are we sure that the invalid fromversion is in the subplaybooks and not the main playbook? Also what is the issue with the loops? Can you please let me know before you merge since this PR seems to affect playbooks

Basically this validation verifies that a main playbook ```fromversion``` must be higher or equal to the ```fromversion``` of its sub-playbooks/used scripts. So regarding the first part of your question, this was the way the validation was implemented in the first place.

This validation failed on the nightly build of the upload flow, it seemed to be flaky, sometimes it passed and sometimes it didn't.

After digging inside into it, I have found out that the validation fails on a specific case where if we have several sub-playbooks with the same ID, then there could be a possibility where by mistake we could fail the validation even in case that a sub-playbook ID with ```fromversion``` < main-playbook ```fromversion``` exist based on their looping order in the code. So we failed the validation even when it shouldn't have failed in the old implemented code.

Along with @JudahSchwartz we have decided to change to way this method is implemented since it was prone to unwanted errors.

The internal logic of the validation has not been changed! That means that the behaviour should be exactly the same as before. The only difference now is the way this method is implemented.

2022-06-21 11:36 UTC, idovandijk commented
> > @GuyAfik are we sure that the invalid fromversion is in the subplaybooks and not the main playbook? Also what is the issue with the loops? Can you please let me know before you merge since this PR seems to affect playbooks
> 
> Basically this validation verifies that a main playbook `fromversion` must be higher or equal to the `fromversion` of its sub-playbooks/used scripts. So regarding the first part of your question, this was the way the validation was implemented in the first place.
> 
> This validation failed on the nightly build of the upload flow, it seemed to be flaky, sometimes it passed and sometimes it didn't.
> 
> After digging inside into it, I have found out that the validation fails on a specific case where if we have several sub-playbooks with the same ID, then there could be a possibility where by mistake we could fail the validation even in case that a sub-playbook ID with `fromversion` <= main-playbook `fromversion` exist based on their looping order in the code. So we failed the validation even when it shouldn't have failed in the old implemented code.
> 
> Along with @JudahSchwartz we have decided to change to way this method is implemented since it was prone to unwanted errors.
> 
> The internal logic of the validation **has not been changed!** That means that the behaviour should be exactly the same as before. The only difference now is the way this method is implemented.

Got it, thanks :)

2022-06-21 12:43 UTC, merged