Markdownlint cherry picked
demisto/demisto-sdk pull request #2198
Opened 2022-06-26 13:49 UTC by JudahSchwartz

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Must have
- [ ] Tests
- [ ] Documentation
- [ ] [VS Code Extension](https://docs.gitlab.com/ee/ci/yaml/#tags)
  - [ ] Functionality implemented in the extension - <u>\<link-to-pr-here\></u>
  - [ ] N/A - Functionality cannot be implemented in the extension because <u>\<add-reason-here\></u>

2022-06-26 14:07 UTC, JudahSchwartz commented on demisto_sdk/commands/doc_reviewer/doc_reviewer.py
> +        self. files: list = []
```suggestion
        self.files: list = []
```

2022-06-28 06:13 UTC, JudahSchwartz commented
@ShahafBenYakir added to the description

2022-06-28 07:03 UTC, dorschw commented on .circleci/config.yml
> +              TEST_FILES=$(echo "$TEST_FILES" | circleci tests split --split-by=timings )
```suggestion
              TEST_FILES=$(echo "$TEST_FILES" | circleci tests split --split-by=timings)
```

2022-06-28 07:14 UTC, dorschw requested changes

2022-06-28 07:14 UTC, dorschw commented on .circleci/config.yml
> +              sudo npm install -g markdownlint-cli
1. Please move this line into `package.json`, and have the CI image install it with `-g` (see `install_node_ci`)
2. Please make sure, before merging, that we install the same under the `content` repo

2022-07-11 09:04 UTC, closed without merging