Downloading the playbooks via the api
demisto/demisto-sdk pull request #2341
Opened 2022-09-08 20:29 UTC by anara123

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: XSUP-12808

## Description
The issue happens because we download the playbook from the custom bundle. Instead we will download the playbook via XSOAR API.
Which will download the playbook via the field scriptName and not script.

## Screenshots
Paste here any images that will help the reviewer

## Must have
- [ ] Tests
- [ ] Documentation
- [ ] [VS Code Extension](https://docs.gitlab.com/ee/ci/yaml/#tags)
  - [ ] Functionality implemented in the extension - <u>\<link-to-pr-here\></u>
  - [ ] N/A - Functionality cannot be implemented in the extension because <u>\<add-reason-here\></u>

2022-09-14 06:56 UTC, dantavori requested changes

2022-09-14 06:56 UTC, dantavori commented on demisto_sdk/commands/download/downloader.py
> +                            if playbook_name not in self.input_files:
when self.all_custom_content flag is True, self.input_files at this stage still doesn't contain the playbook name (only after self.handle_all_custom_content_flag()) so we can't rely on it. Let's make sure handle_all_custom_content_flag is called before this function.

2022-09-14 06:56 UTC, dantavori commented on demisto_sdk/commands/download/downloader.py
>                          file.write(string_to_write)
let's keep using `with` or call `close()`

2022-09-14 06:56 UTC, dantavori commented on demisto_sdk/commands/download/downloader.py
> +                    if not self.list_files and re.search(r'playbook-.*\.yml', member.name):
can we move this if block to a separate method handle_playbook_download()?

2022-09-14 06:56 UTC, dantavori commented on demisto_sdk/tests/integration_tests/download_integration_test.py
> +    # mocker.patch.object(demisto_client, 'generic_request_func', return_value={'status_code': 200})
```suggestion
```

2022-09-14 06:56 UTC, dantavori commented on demisto_sdk/tests/integration_tests/download_integration_test.py
> +        #     f2.write(string_to_write)
```suggestion
```

2022-09-14 10:58 UTC, dorschw commented on demisto_sdk/commands/download/downloader.py
>                          file.write(string_to_write)
with significantly preferred

2022-09-16 14:41 UTC, dantavori approved these changes

2022-09-16 14:41 UTC, dantavori commented on demisto_sdk/commands/download/downloader.py
> +                if status_code < 200 and status_code >= 300:
```suggestion
                if status_code < 200 or status_code >= 300:
```

2022-09-17 18:01 UTC, merged