uuid to names
demisto/demisto-sdk pull request #2572
Opened 2022-12-14 09:46 UTC by merit-maita

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Must have
- [ ] Tests
- [ ] Documentation
- [ ] [VS Code Extension](https://docs.gitlab.com/ee/ci/yaml/#tags)
  - [ ] Functionality implemented in the extension - <u>\<link-to-pr-here\></u>
  - [ ] N/A - Functionality cannot be implemented in the extension because <u>\<add-reason-here\></u>

2022-12-14 16:29 UTC, DeanArbel requested changes
Looks good, just make sure to extract the content items identifiers to constants, and tag @dorschw as a reviewer once you're done.

2022-12-14 16:29 UTC, DeanArbel commented on demisto_sdk/commands/download/downloader.py
> +            # this will make sure that we save the downloaded files in the custom content temp dir
nice

2022-12-14 16:29 UTC, DeanArbel commented on demisto_sdk/commands/download/downloader.py
> +        if re.search(r'^[0-9a-fA-F]{8}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{12}$',
Please extract the regex expression to the `constants.py` file, ideally reusing the other existing `constants` to construct the `regex`.

2022-12-14 16:29 UTC, DeanArbel commented on demisto_sdk/commands/download/downloader.py
> +        if not self.list_files and re.search(r'incidentfield-.*\.json', member_name):
Same as above.

2022-12-14 16:29 UTC, DeanArbel commented on demisto_sdk/commands/download/downloader.py
> +        if not self.list_files and re.search(r'playbook-.*\.yml', member_name):
Same as above.

2022-12-14 16:29 UTC, DeanArbel commented on demisto_sdk/commands/download/downloader.py
> +        if not self.list_files and re.search(r'layout.*\.json', member_name):
Same as above.

2022-12-18 08:15 UTC, DeanArbel approved these changes
Good job!

2022-12-18 09:56 UTC, dorschw reviewed
Nicely done

2022-12-18 09:56 UTC, dorschw commented on CHANGELOG.md
> +* Fixed an issue where custom scripts names were replaced with uuid in IncidentFields and Layouts.
```suggestion
* Fixed an issue in **download**, where names of custom scripts were replaced with UUIDs in IncidentFields and Layouts.
```

2022-12-18 09:56 UTC, dorschw commented on demisto_sdk/commands/download/downloader.py
> +                                                                    scripts_mapper[file_json_object.get('script')])
please replace the multiple `.get('script')`s with a single call saving its value as a variable.

2022-12-18 09:56 UTC, dorschw commented on demisto_sdk/commands/download/downloader.py
> +                    for item in items:
```suggestion
            for tab in file_json_object.get('detailsV2', {}).get('tabs', ()):
                for section in tab.get('sections', ()):
                    for item in section.get('items', ()):
```

2022-12-18 09:56 UTC, dorschw commented on demisto_sdk/commands/download/downloader.py
> +                                                                  scripts_mapper[item.get('scriptId')])
please refrain from repetitive `.get` calls - use a variable instead.

2022-12-18 09:56 UTC, dorschw commented on demisto_sdk/commands/common/constants.py
> +LAYOUT_REGEX = r'layout.*\.json'
```suggestion
INCIDENT_FIELD_FILE_NAME_REGEX = r'incidentfield-.*\.json'

LAYOUT_FILE_NAME__REGEX = r'layout.*\.json'
```

2022-12-18 11:52 UTC, merged