fix bad path for exception
demisto/demisto-sdk pull request #2584
Opened 2022-12-15 15:57 UTC by JudahSchwartz

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Must have
- [ ] Tests
- [ ] Documentation
- [ ] [VS Code Extension](https://docs.gitlab.com/ee/ci/yaml/#tags)
  - [ ] Functionality implemented in the extension - <u>\<link-to-pr-here\></u>
  - [ ] N/A - Functionality cannot be implemented in the extension because <u>\<add-reason-here\></u>

2022-12-15 15:59 UTC, JudahSchwartz commented
we're using pypdf2 1.28.6, which has the exception under errors

2022-12-15 16:00 UTC, dorschw approved these changes

2022-12-15 16:02 UTC, dorschw requested changes
Please update pyproject.toml to use `pypdf=^1.28.6`, then run `poetry lock`.

2022-12-19 09:18 UTC, dorschw approved these changes

2022-12-19 09:35 UTC, merged