Added DEMISTO_SDK_OFFLINE_ENV env var for working offline
demisto/demisto-sdk pull request #3034
Opened 2023-05-18 13:54 UTC by adi88d

## Related Issues
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-5953

## Description

2023-07-06 09:23 UTC, dorschw commented on demisto_sdk/__main__.py
> +            if os.getenv(ENV_SDK_WORKING_OFFLINE, "").lower() == "yes":
please use `arg2bool` instead of comparing to `yes`

2023-07-06 09:23 UTC, dorschw commented on demisto_sdk/__main__.py
> +        sys.exit(1)
do not use sys.exit. Raise an exception instead. No need to log in case of an exception

2023-07-06 09:23 UTC, dorschw requested changes
see comments

2023-07-13 09:06 UTC, dorschw commented on demisto_sdk/commands/common/tools.py
> +        return default_value
is it used anywhere?

2023-07-13 09:06 UTC, dorschw commented on demisto_sdk/commands/common/tools.py
> +        return default_value
I think we should treat `None` as _do not return a default value, always raise the exception_. 
Let's add this logic, and document it in the docstrings.

2023-07-13 14:01 UTC, adi88d commented on demisto_sdk/commands/common/tools.py
> +def is_sdk_defined_working_offline() -> bool:
done

2023-07-16 16:13 UTC, dorschw commented on README.md
> +   When its set, the sdk will skip the places that internet connection is required for them instead of trying to do the requests.
Please have @ShirleyDenkberg review this, as well as the error messages.

2023-07-16 16:14 UTC, dorschw commented on demisto_sdk/__main__.py
> +        or not is_sdk_defined_working_offline()
shouldn't it be `and`, instead of `or`?

2023-07-16 16:14 UTC, dorschw commented on demisto_sdk/commands/common/tools.py
> +    pass
please explain in two sentences what this is for.

2023-07-16 16:15 UTC, dorschw commented on demisto_sdk/commands/common/tools.py
> +            raise NoInternetConnectionException()
```suggestion
            raise NoInternetConnectionException
```

2023-07-16 16:15 UTC, dorschw commented on demisto_sdk/commands/common/tools.py
> +    global OFFLINE_MODE
don't use globals, use `constants.py` instead.

2023-07-17 14:27 UTC, ShirleyDenkberg commented
@dorschw Doc review completed.

2023-07-20 15:06 UTC, dorschw requested changes

2023-07-23 13:41 UTC, dorschw commented on demisto_sdk/commands/common/tools.py
> +class NoInternetConnectionException(Exception):
```suggestion
class NoInternetConnectionException(Exception):
"""
This exception israised in methods that require an internet connection, when the SDK is defined as working offline.
"""
```

2023-07-23 13:55 UTC, dorschw commented on demisto_sdk/commands/download/downloader.py
> +            logger.info(f"format is not supported when the DEMISTO_SDK_OFFLINE_ENV environment variable is set.")
```suggestion
            logger.info(f"format is not supported when the DEMISTO_SDK_OFFLINE_ENV environment variable is set, skipping it.")
```

2023-07-23 13:55 UTC, dorschw approved these changes

2023-07-23 15:37 UTC, merged