Validate bug
demisto/demisto-sdk pull request #3037
Opened 2023-05-18 15:39 UTC by merit-maita

## Related Issues
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-6552

## Description
fixes an issue in validate command where reputation commands outputs where not checked in new content

2023-05-21 08:23 UTC, YuvHayun requested changes
Nice catch!
Did you get to test it's working?

2023-05-21 08:23 UTC, YuvHayun commented on CHANGELOG.md
> +* Fixed an issue in *validate* where reputation command's outputs where not checked in new content.
```suggestion
* Fixed an issue where *validate* reputation commands outputs weren't checked for new contribution content.
```

2023-05-21 15:16 UTC, merit-maita commented
> Nice catch! Did you get to test it's working?

yes i did, i added a new pack with reputation commands, lacking some outputs, it caught it

2023-05-21 15:22 UTC, DeanArbel approved these changes

2023-05-23 13:09 UTC, YuvHayun approved these changes

2023-05-24 16:57 UTC, merged