added logs
demisto/demisto-sdk pull request #3095
Opened 2023-06-04 10:25 UTC by dansterenson

## Related Issues
fixes:

## Description

2023-06-05 08:37 UTC, ilaner approved these changes

2023-06-05 08:37 UTC, ilaner requested changes
merge from master and change the changelog

2023-06-05 12:14 UTC, dorschw commented on demisto_sdk/commands/init/contribution_converter.py
> +def get_previous_line(index: int, lines: List[str]):
```suggestion
def get_previous_nonempty_line(index: int, lines: List[str]):
```

2023-06-05 12:15 UTC, dorschw commented on demisto_sdk/commands/init/contribution_converter.py
> +def get_previous_line(index: int, lines: List[str]):
i'd provide `lines` before `index`

2023-06-05 12:56 UTC, dorschw approved these changes

2023-06-06 08:36 UTC, ilaner approved these changes

2023-06-06 08:41 UTC, merged