default yaml,json handlers
demisto/demisto-sdk pull request #3308
Opened 2023-07-17 10:09 UTC by dorschw

replace default handlers with a constant

2023-07-17 15:35 UTC, kobymeir requested changes

2023-07-17 15:35 UTC, kobymeir commented on demisto_sdk/commands/init/templates/BaseIntegration/BaseIntegration_test.py
> +    DEFAULT_YAML_HANDLER as yaml,
no need for yaml?

2023-07-17 15:35 UTC, kobymeir commented on demisto_sdk/commands/init/templates/BaseScript/BaseScript_test.py
> +    DEFAULT_YAML_HANDLER as yaml,
no need for yaml?

2023-07-17 15:35 UTC, kobymeir commented on demisto_sdk/commands/generate_test_playbook/test_playbook_generator.py
> +from demisto_sdk.commands.common.handlers import DEFAULT_YAML_HANDLER as yaml
join imports

2023-07-17 15:50 UTC, dorschw commented on demisto_sdk/commands/generate_integration/code_generator.py
>  yaml = YAML_Handler(width=50000)
different issue

2023-07-17 15:53 UTC, dorschw commented on demisto_sdk/commands/generate_test_playbook/test_playbook_generator.py
> +from demisto_sdk.commands.common.handlers import DEFAULT_YAML_HANDLER as yaml
ruff I001 says no

2023-07-17 15:53 UTC, dorschw commented on demisto_sdk/commands/generate_integration/code_generator.py
> +from demisto_sdk.commands.common.handlers import DEFAULT_JSON_HANDLER as json
ruff I001 says no

2023-07-17 15:54 UTC, dorschw commented on demisto_sdk/commands/pre_commit/tests/pre_commit_test.py
> +    yaml,
here it's by design, as it's only for mocking.

2023-07-17 16:06 UTC, dorschw commented on demisto_sdk/commands/common/tools.py
> +)
Asked them [here](https://github.com/astral-sh/ruff/issues/5836)

2023-07-18 09:47 UTC, kobymeir requested changes

2023-07-18 09:47 UTC, kobymeir commented on demisto_sdk/commands/content_graph/objects/pack.py
> +from demisto_sdk.commands.common.handlers import DEFAULT_JSON_HANDLER as json
it was on line 19 before, now on 85. why not move the import up before the if statement

2023-07-18 11:54 UTC, kobymeir approved these changes

2023-07-18 11:54 UTC, merged