Modeling Rules Test Re-Generate Event Id Field
demisto/demisto-sdk pull request #3396
Opened 2023-07-23 13:43 UTC by AradCarmi

## Related Issues
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-7466).

## Description
- Remove the event ID from the dataset.
- Create a new event ID.
- Verify the new event ID is unique.

2023-07-31 20:17 UTC, dantavori commented on demisto_sdk/commands/test_content/xsiam_tools/test_data.py
> +        super().__init__(**data)
less recommended to impl a c'tor in pydantic, check if we can avoid that

2023-08-01 14:40 UTC, daryakoval requested changes

2023-08-01 14:40 UTC, daryakoval commented on demisto_sdk/commands/test_content/test_modeling_rule/test_modeling_rule.py
>  def validate_expected_values(
Let's split this function into 2 different atomic logics. 
With your change, it is not `validate_expected_values`... It is doing 2 different checks if some flag is set to true. 
This is very confusing. 
Let's discuss tomorrow my suggestion.

2023-08-07 13:47 UTC, daryakoval approved these changes

2023-08-09 08:15 UTC, AradCarmi commented
Closing because merged the changes with this [PR](https://github.com/demisto/demisto-sdk/pull/3447).

2023-08-09 08:15 UTC, closed without merging