Add lint erros and run on branch only
demisto/demisto-sdk pull request #3439
Opened 2023-08-02 15:01 UTC by DinaMeylakh

## Related Issues
fixes:

## Description

2023-08-02 16:19 UTC, dorschw commented on CHANGELOG.md
> +* **lint** will now fail on `demisto.results` and `return_outputs` usage, when a pack is `xsoar` or `partner` supported.
pull from master and sync the changelog please

2023-08-09 10:52 UTC, eyalpalo requested changes
Nice!

2023-08-09 10:52 UTC, eyalpalo commented on demisto_sdk/commands/lint/resources/pylint_plugins/base_checker.py
> -
Please revert

2023-08-09 11:15 UTC, dorschw commented on demisto_sdk/commands/lint/commands_builder.py
> +    support_level: str = "base",
Consider using `Literal` as the type hint here

2023-08-09 11:37 UTC, eyalpalo approved these changes

2023-08-09 12:19 UTC, merged