Ciac 7465/add delete existing data set flag
demisto/demisto-sdk pull request #3447
Opened 2023-08-07 11:10 UTC by AradCarmi

## Related Issues
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-7465

## Description
Added the -dd flag to the **modeling-rules** *test* command when enabled it is deleting the dataset if it exists on the tenant.

2023-08-14 13:43 UTC, daryakoval commented on CHANGELOG.md
> +* Added the *--delete_existing_dataset/-dd* flag to the **modeling-rules test** command to delete an existing dataset in the tenant.
What about - verify_event_id_does_not_exist_on_tenant ?

2023-08-14 13:43 UTC, daryakoval commented on demisto_sdk/commands/test_content/test_modeling_rule/test_modeling_rule.py
> +    raise typer.Exit(1)
Why fail the test on it? 
In the previous PR this was not like this?
Where do you replace the existing uuid with new one?

2023-08-14 14:55 UTC, dantavori commented on demisto_sdk/commands/test_content/test_modeling_rule/test_modeling_rule.py
> +    for i in range(timeout // interval):
```suggestion
    query = f"config timeframe = 10y | dataset = {dataset}"
    num_of_attempts = timeout // interval
    for i in range(num_of_attempts):
```

2023-08-14 14:56 UTC, dantavori commented on demisto_sdk/commands/test_content/test_modeling_rule/test_modeling_rule.py
> +            if i + 1 == timeout // interval:
```suggestion
            if i + 1 == num_of_attempts:
```

2023-10-03 10:50 UTC, kobymeir requested changes

2023-10-03 10:50 UTC, kobymeir commented on demisto_sdk/commands/test_content/test_modeling_rule/test_modeling_rule.py
> +            f"Validate event_id_does_not_exist_on_tenant {modeling_rule.path} dataset:{rule.dataset} "
```suggestion
            f"Validate event_id_does_not_exist_on_tenant {get_relative_path_to_content(modeling_rule.path)} dataset:{rule.dataset} "
```

2023-10-03 10:50 UTC, kobymeir commented on demisto_sdk/commands/test_content/test_modeling_rule/test_modeling_rule.py
> +            result = xsiam_execute_query(xsiam_client, query)
```suggestion
                result = retrying_caller(xsiam_execute_query, xsiam_client, query)
```

2023-10-03 10:50 UTC, kobymeir commented on demisto_sdk/commands/test_content/test_modeling_rule/test_modeling_rule.py
> +                ]
```suggestion
                validate_event_id_does_not_exist_on_tenant_test_case.result += [Error(error_msg)
                ]
```

2023-10-03 10:50 UTC, kobymeir commented on demisto_sdk/commands/test_content/test_modeling_rule/test_modeling_rule.py
> +                validate_event_id_does_not_exist_on_tenant_test_case.result += [
no need to add a success to the `.result` only errors

2023-10-03 10:50 UTC, kobymeir commented on demisto_sdk/commands/test_content/test_modeling_rule/test_modeling_rule.py
> +    error_msg = "[red]The event id already exists in the tenant[/red]"
error message that's being added to TestCase data, can't contain color markers

2023-10-03 10:50 UTC, kobymeir commented on demisto_sdk/commands/test_content/test_modeling_rule/test_modeling_rule.py
> +        help=("Deletion of the existing dataset from the tenant. Default: False."),
```suggestion
        help="Deletion of the existing dataset from the tenant. Default: False.",
```

2023-10-10 10:32 UTC, kobymeir approved these changes

2023-10-11 10:37 UTC, merged