[pre-commit ruff] Run with nightly_ruff.toml when running wite --all flag
demisto/demisto-sdk pull request #3640
Opened 2023-09-14 12:58 UTC by mmhw

## Related Issues
Related: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-8236)

## Description
Modified the `ruff` pre-commit hook to run with `--config=nightly_ruff.toml` flag when running **pre-commit** command wite the `--all` flag.

2023-09-27 18:22 UTC, ilaner requested changes
Very good job.
See comments

2023-09-27 18:22 UTC, ilaner commented on demisto_sdk/__main__.py
> +    "--mode",
you can add enum to the mode to allow only specific values. See how we do that in `marketplace` option in other places

2023-09-27 18:22 UTC, ilaner commented on demisto_sdk/__main__.py
> +    if mode and mode not in PRE_COMMIT_MODE_OPTIONS:
that should be handles by click, see comment above.

2023-09-27 18:22 UTC, ilaner commented on demisto_sdk/commands/pre_commit/hooks/hook.py
> +PRE_COMMIT_MODE_OPTIONS = NIGHTLY_MODE
lets make it an enum instead of variable

2023-09-27 18:22 UTC, ilaner commented on demisto_sdk/commands/pre_commit/hooks/validate_format.py
>              self.base_hook["args"].append("-i")
good idea. This way if running on regular mode we will run with `-i` on git files, which will identify more problems.

2023-09-28 08:52 UTC, dorschw commented on CHANGELOG.md
> +* Added the *--mode* flag to the **pre-commit** command, to run pre-commit with special mode.
What is a `mode`? What modes are possible?

2023-09-28 08:52 UTC, dorschw commented on CHANGELOG.md
> +* Added the *--mode* flag to the **pre-commit** command, to run pre-commit with special mode.
flag = boolean argument.
otherwise, it's an argument

2023-09-28 08:52 UTC, dorschw commented on demisto_sdk/commands/pre_commit/hooks/hook.py
> +        mode: str = None,
```suggestion
        mode: Optional[str] = None,
```

2023-09-28 08:52 UTC, dorschw commented on demisto_sdk/commands/pre_commit/hooks/hook.py
> +        hook[args_key] = [value]
use a `defaultdict(list)` instead

2023-09-28 08:52 UTC, dorschw commented on demisto_sdk/commands/pre_commit/pre_commit_command.py
> +    mode: str = None,
```suggestion
    mode: Optional[str] = None,
```

2023-09-28 10:07 UTC, ilaner approved these changes
Great job!

2023-09-28 11:07 UTC, merged