Added XSOAR-linter to pre-commit
demisto/demisto-sdk pull request #3962
Opened 2024-01-18 11:51 UTC by dansterenson

## Related Issues
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-7062

2024-01-21 09:05 UTC, dorschw commented on demisto_sdk/commands/pre_commit/hooks/xsoar_linter.py
> +            if (py_ver := integration_script_obj.python_version) and Version(py_ver).major < 3:
If one content item is py2, we'll have this env var set for all items?

2024-01-21 09:06 UTC, dorschw commented on demisto_sdk/commands/pre_commit/hooks/xsoar_linter.py
> +                    if file.suffix == ".py" and '_test' not in file.name
```suggestion
                    if file.suffix == ".py" and not file.name.endswith('_test')
```

2024-02-05 08:53 UTC, ilaner requested changes
Good job
See comments, and add test for the xsoar-linter command.

2024-02-05 08:53 UTC, ilaner commented on demisto_sdk/commands/xsoar_linter/xsoar_linter.py
> +xsoar_linter_app = typer.Typer(name="Pre-Commit")
please remove

2024-02-05 08:53 UTC, ilaner commented on demisto_sdk/commands/xsoar_linter/xsoar_linter.py
> +def process_file(file_path):
types and docstrings

2024-02-05 08:53 UTC, ilaner commented on demisto_sdk/commands/xsoar_linter/xsoar_linter.py
> +    return return_code, errors_str
retuned NamedTuple/dataclass

2024-02-05 08:53 UTC, ilaner commented on demisto_sdk/commands/xsoar_linter/xsoar_linter.py
> +        pattern = re.compile(r'^/[^:\n]+:\d+:\d+: E\d+ .*$', re.MULTILINE)
make comment and use global var

2024-02-13 13:08 UTC, ilaner approved these changes
Good job!

2024-02-13 15:08 UTC, merged