validate metadata changes and update-release-notes
demisto/demisto-sdk pull request #3972
Opened 2024-01-23 13:47 UTC by michal-dagan

## Related Issues
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-9526

## Description
- Updated the **validate** command (`PA114`) to verify the "currentVersion" field was raised in the pack_metadata when changing the following metadata fields (PACK_METADATA_REQUIRE_RN_FIELDS) in the pack_metadata file:

  support
  serverMinVersion
  dependencies
  marketplaces
  name
  price
  excludedDependencies

- Added support for **update-release-notes** command to update release notes when changing those fields in the pack_metadata file.

Now when running the following command: `demisto-sdk update-release-notes` when changing those fields
The results will look like the following:

```

## PackName

- %%UPDATE_RN%%

```

2024-02-05 09:50 UTC, michal-dagan commented on demisto_sdk/commands/update_release_notes/update_rn.py
> +                "fromversion": get_from_version_at_update_rn(packfile)
Adding support for update-release-notes in case of pack_metadata changes results in a file without the "fromversion" field.

2024-02-05 10:02 UTC, michal-dagan commented on demisto_sdk/commands/common/tools.py
> +                return ""
After calling `get_latest_release_notes_text` we call `self.update_existing_rn` and then use "re.sub" with 'None' value

2024-02-18 12:33 UTC, YuvHayun requested changes
Nice job!
Minor comments.

2024-02-22 13:15 UTC, michal-dagan commented on demisto_sdk/commands/common/constants.py
> +    {  # TODO - to change to PACK_METADATA_NOT_REQUIRE_RN_FIELDS
subject to changes, if one of you thinks of other fields that require RN - version bump
https://docs.google.com/spreadsheets/d/16mtI5YrWvDJdsIPkfmqqsTFg97QCDPz04ITIJuOLMxI/edit#gid=1167204366

2024-02-28 11:43 UTC, YuvHayun approved these changes
Nice!

2024-02-28 11:43 UTC, YuvHayun commented on demisto_sdk/commands/common/constants.py
> +    {  # TODO - to change to PACK_METADATA_NOT_REQUIRE_RN_FIELDS
Looks good by me, just remove the TODO

2024-02-28 11:59 UTC, bziser approved these changes

2024-02-28 12:01 UTC, michal-dagan commented on demisto_sdk/commands/common/constants.py
> +    {  # TODO - to change to PACK_METADATA_NOT_REQUIRE_RN_FIELDS
```suggestion
    {
```

2024-02-28 13:19 UTC, merged