Validate image path in integration exists and author image in pack exists
demisto/demisto-sdk pull request #4069
Opened 2024-02-20 16:19 UTC by tcarmeli1

## Description
Validate an integration has an image path and a pack has an author image path
## Related Issues:
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-9800 , https://jira-dc.paloaltonetworks.com/browse/CIAC-9797

2024-02-20 19:27 UTC, jbabazadeh requested changes
Great work!! :) 
please see my comments

2024-02-20 19:27 UTC, jbabazadeh commented on demisto_sdk/commands/validate/validators/IM_validators/IM109_author_image_exists_validation.py
> +    error_message = "author_image_doesn't_exists"
```suggestion
    error_message = "Partners must provide a non-empty author image."
```

2024-02-25 11:48 UTC, YuvHayun requested changes
Looks good!
Minor comments.

2024-02-25 11:48 UTC, YuvHayun commented on CommonServerUserPython.py
?

2024-02-25 11:48 UTC, YuvHayun commented on demisto_sdk/commands/validate/validators/IM_validators/IM100_image_exists_validation.py
> +    error_message = "You've created/modified a yml or package without providing an image as a .png file , please add an image in order to proceed."
Let's also add the expected file path.

2024-02-25 11:48 UTC, YuvHayun commented on demisto_sdk/commands/validate/validators/IM_validators/IM109_author_image_exists_validation.py
> +    error_message = "Partner, You've created/modified a yml or package without providing an author image as a .png file , please add an image in order to proceed."
Also here, let's add the path.

2024-02-25 11:48 UTC, YuvHayun commented on demisto_sdk/commands/validate/validators/IM_validators/IM109_author_image_exists_validation.py
> +    is_auto_fixable = False
```suggestion
    expected_git_statuses = [GitStatuses.ADDED, GitStatuses.MODIFIED]
```

2024-02-25 11:48 UTC, YuvHayun commented on demisto_sdk/commands/validate/validators/IM_validators/IM100_image_exists_validation.py
> +    is_auto_fixable = False
```suggestion
    expected_git_statuses = [GitStatuses.ADDED, GitStatuses.MODIFIED]
```

2024-02-26 12:57 UTC, YuvHayun requested changes

2024-02-26 12:57 UTC, YuvHayun commented on demisto_sdk/commands/validate/validators/IM_validators/IM100_image_exists_validation.py
> +    error_message = "You've created/modified a yml or package without providing an image as a .png file, please add an image"
```suggestion
    error_message = "You've created/modified a yml or package without providing an image as a .png file. Please make sure to add an image at {}."
```

2024-02-26 12:57 UTC, YuvHayun commented on demisto_sdk/commands/validate/validators/IM_validators/IM100_image_exists_validation.py
> +                message=f"{self.error_message} with the following path {content_item.name}_image.png in order to proceed.",
```suggestion
                message=self.error_message.format(content_item.image_file),
```

2024-02-26 12:57 UTC, YuvHayun commented on demisto_sdk/commands/validate/validators/IM_validators/IM109_author_image_exists_validation.py
> +    error_message = "Partner, You've created/modified a yml or package without providing an author image as a .png file, please add an image with the following path Author_image.png in order to proce
```suggestion
    error_message = "You've created/modified a yml or package in a partner supported pack without providing an author image as a .png file. Please make sure to add an image at {}."
```

2024-02-26 12:57 UTC, YuvHayun commented on demisto_sdk/commands/validate/validators/IM_validators/IM109_author_image_exists_validation.py
> +                validator=self, message= self.error_message, content_object=content_item
```suggestion
                validator=self, message=self.error_message.format(content_item.author_image_path), content_object=content_item
```

2024-03-03 09:04 UTC, jbabazadeh approved these changes
Great Work!

2024-03-04 06:06 UTC, merged