Yr/ convert bc108 and bc109 to the new validator
demisto/demisto-sdk pull request #4070
Opened 2024-02-20 16:32 UTC by RosenbergYehuda

## Related Issues
fixes:

## Description

2024-02-25 11:30 UTC, YuvHayun requested changes
Looks good.
I added a few comments.
Also, let's remove the use of conditions inside the tests.
There shouldn't be any logic & conditions inside the tests. If needed, add more test functions, but right now it's really hard to read, debug, and undersstand.

2024-02-25 18:05 UTC, RosenbergYehuda commented on demisto_sdk/commands/validate/validators/BC_validators/BC108_was_marketplace_modified.py
> +    expected_git_statuses = [GitStatuses.MODIFIED]
Why? If you only renamed the file, how is that relevent to this validation?

2024-02-25 18:19 UTC, RosenbergYehuda commented on demisto_sdk/commands/validate/tests/test_tools.py
> +def create_pack_object(
I missed that one....

2024-02-28 13:18 UTC, RosenbergYehuda commented on demisto_sdk/commands/validate/validators/BC_validators/BC108_was_marketplace_modified.py
> +    expected_git_statuses = [GitStatuses.MODIFIED]
Done

2024-02-28 15:37 UTC, YuvHayun approved these changes

2024-02-28 15:37 UTC, YuvHayun commented on demisto_sdk/commands/validate/tests/test_tools.py
> +from demisto_sdk.commands.content_graph.objects.pack import Pack
?

2024-02-28 17:14 UTC, merged