Adding the defaultDataSource field to the pack metadata
demisto/demisto-sdk pull request #4139
Opened 2024-03-18 08:43 UTC by amshamah419

## Related Issues
fixes:https://jira-dc.paloaltonetworks.com/browse/CIAC-9753

## Description

2024-04-08 06:40 UTC, yuvalbenshalom reviewed
preliminary review, see my comment.

2024-04-08 06:40 UTC, yuvalbenshalom commented on demisto_sdk/commands/validate/validators/PA_validators/PA131_is_default_datasource.py
> +                    if command.name == "fetch-incidents":
please change this check to the check if "isfetch: true" "isFetchSamples: true" exists in the yml.
note that in isFetchSamples: true we need to filter out feeds.

2024-05-22 13:34 UTC, jbabazadeh requested changes
Nice job! ⭐ 
please see my comments.

2024-05-22 13:34 UTC, jbabazadeh commented on demisto_sdk/commands/content_graph/objects/integration.py
> +                or self.is_fetch_events_and_assets
we already talk about it you can ignore.

2024-05-22 17:20 UTC, jbabazadeh requested changes
great work on the validations!

2024-05-22 17:20 UTC, jbabazadeh commented on demisto_sdk/commands/validate/validators/PA_validators/PA132_is_valid_default_datasource.py
> +    fix_message = "Set the 'defaultDataSource' for '{0}' pack to the '{1}' integration (changed from display name to id)."
Updated the 'defaultDataSource' for the '{0}' pack to use the '{1}' integration ID instead of the display name that previously used.

2024-05-22 19:41 UTC, BEAdi commented on demisto_sdk/commands/content_graph/objects/pack_metadata.py
> +    def _set_default_data_source(self, content_items: PackContentItems) -> None:
I kept the current logic of setting the value in an internal method and getting the value in a public one. `is_data_source` should be exposed outside, but setting it is called from another internal method.

2024-05-23 07:38 UTC, BEAdi commented on demisto_sdk/commands/content_graph/objects/pack_metadata.py
> +            else []
I removed the `else` case as we do not let `data_source_id` to be optional.

2024-05-26 10:54 UTC, BEAdi commented on demisto_sdk/commands/generate_docs/generate_integration_doc.py
> +                        "",
Yes, it will be added only to new generated readmes (not those that we only add new commands to, same as the rest of the headers).

2024-05-27 07:24 UTC, jbabazadeh approved these changes

2024-05-27 08:41 UTC, merged