refactored validate for DA
demisto/demisto-sdk pull request #4264
Opened 2024-05-07 10:16 UTC by merit-maita

## Related Issues
fixes:

## Description

2024-05-09 07:41 UTC, YuvHayun requested changes
Looks good so far, see my comment regarding the content item data.

2024-05-09 07:41 UTC, YuvHayun commented on demisto_sdk/commands/validate/validators/DA_validators/DA101_dashboard_contains_necessary_fields.py
> +        "the '{0}' fields are missing from {1} and need to be added."
```suggestion
        "The '{0}' fields are missing from {1} and need to be added."
```

2024-05-09 07:41 UTC, YuvHayun commented on demisto_sdk/commands/validate/validators/DA_validators/DA101_dashboard_contains_necessary_fields.py
> +        "the '{0}' fields are missing from {1} Widget in {2} and need to be added."
```suggestion
        "The '{0}' fields are missing from {1} Widget in {2} and need to be added."
```

2024-05-09 07:41 UTC, YuvHayun commented on demisto_sdk/commands/validate/validators/DA_validators/DA101_dashboard_contains_necessary_fields.py
> +            )
We shouldn't work with the content item data.
We're using graph objects here so the idea is to use the object fields - if necessary then you can add that to the graph object.

2024-05-16 08:02 UTC, YuvHayun approved these changes
Looks good!
See my comments.

2024-05-16 08:13 UTC, merit-maita commented on demisto_sdk/commands/validate/validators/DA_validators/DA101_dashboard_contains_necessary_fields.py
> +    related_field = ""
in the previous validation, it does not have a related field

2024-05-16 08:13 UTC, merit-maita commented on demisto_sdk/commands/validate/validators/DA_validators/DA100_dashboard_contains_forbidden_fields.py
> +    related_field = ""
in the previous validation, it does not have a related field

2024-05-16 09:15 UTC, merged