Fix gen-docs Command Sections Parsing
demisto/demisto-sdk pull request #4303
Opened 2024-05-28 07:56 UTC by kgal-pan

## Related Issues
fixes:https://jira-dc.paloaltonetworks.com/browse/CIAC-10635

## Description
The PR includes a fix and improved implementation of finding the commands' sections within the integration `README.md` which used when updating modified commands within the integration `README.md`

2024-06-04 10:34 UTC, samuelFain requested changes
Nice!
@kgal-pan  Please review my very few comments :)
Also, it would be much appreciated if you could document these changes in [here](https://confluence-dc.paloaltonetworks.com/display/DemistoContent/demisto-sdk+command+related+information).

2024-06-04 10:34 UTC, samuelFain commented on demisto_sdk/commands/generate_docs/README.md
> +## Arguments
Are all the `**Example**` to `##Example` changes fine from a BC point of view?
These are the changes that enables support for code like: `{HEADER_TYPE.H3}`, correct?

2024-06-04 11:02 UTC, kgal-pan commented on .changelog/4303.yml
> +- description: Improved implementation of finding the commands' sections within the integration README.md
https://github.com/demisto/demisto-sdk/pull/4303/commits/87670b3948d41842523d581f2032329df5a7aa99

2024-06-16 09:20 UTC, samuelFain approved these changes
Nice!

2024-06-16 09:24 UTC, merged