refactored is_taskid_equals_id validation
demisto/demisto-sdk pull request #4358
Opened 2024-06-17 12:44 UTC by noydavidi

## Related Issues
fixes:

## Description

2024-06-17 13:19 UTC, YuvHayun commented on demisto_sdk/commands/validate/tests/PB_validators_test.py
> +    }
You can remove this part, the object returned from create_playbook_object() should contain tasks and be valid already.

2024-06-17 13:20 UTC, YuvHayun commented on demisto_sdk/commands/validate/validators/PB_validators/PB109_is_taskid_equals_id.py
> +        "Check that taskid field and id field under task field contains equal values"
```suggestion
        "Check that taskid field and id field under task field contains equal values."
```

2024-06-17 13:20 UTC, YuvHayun commented on demisto_sdk/commands/validate/validators/PB_validators/PB109_is_taskid_equals_id.py
> +    rationale = ""
Make sure to fill this field.

2024-06-17 13:21 UTC, YuvHayun commented on demisto_sdk/commands/validate/validators/PB_validators/PB109_is_taskid_equals_id.py
> +    related_field = ""
Make sure to fill this field.

2024-06-17 13:23 UTC, YuvHayun commented on demisto_sdk/commands/validate/validators/PB_validators/PB109_is_taskid_equals_id.py
> +                is_valid_task = taskid == inner_id
Let's make a list of all the problematic tasks and then retrieve it with some generic message.

2024-06-18 12:32 UTC, YuvHayun requested changes
Nice!
Minor comments.

2024-06-18 12:32 UTC, YuvHayun commented on demisto_sdk/commands/validate/sdk_validation_config.toml
> +    "PB100", "PB101","PB103","PB104", "PB105", "PB108", "PB109", "PB123", "PB126",
Let's also add this validation to run on use_git.

2024-06-18 12:32 UTC, YuvHayun commented on demisto_sdk/commands/validate/validators/PB_validators/PB109_is_taskid_equals_id.py
> +ContentTypes = TestPlaybook
```suggestion
ContentTypes = BasePlaybook
```

2024-06-18 12:32 UTC, YuvHayun commented on demisto_sdk/commands/validate/validators/PB_validators/PB109_is_taskid_equals_id.py
> +    rationale = "Playbooks task ids should be in uuid format"
This isn't what you're checking in the validation, change the rationale.

2024-06-18 12:32 UTC, YuvHayun commented on demisto_sdk/commands/validate/validators/PB_validators/PB109_is_taskid_equals_id.py
> +    related_field = "1"
```suggestion
    related_field = "tasks"
```

2024-06-18 12:32 UTC, YuvHayun commented on demisto_sdk/commands/validate/validators/PB_validators/PB109_is_taskid_equals_id.py
> +                            not_valid_tasks,
```suggestion
                            ", ".join(not_valid_tasks),
```
This will print it more readable.

2024-06-19 13:02 UTC, JudahSchwartz approved these changes
looks great! @YuvHayun can you rereview?

2024-06-19 13:35 UTC, YuvHayun approved these changes

2024-06-19 13:36 UTC, YuvHayun commented on demisto_sdk/commands/validate/tests/PB_validators_test.py
> +>>>>>>> master
```suggestion
from demisto_sdk.commands.validate.validators.PB_validators.PB109_is_taskid_equals_id import (
    IsTaskidDifferentFromidValidator,
from demisto_sdk.commands.validate.validators.PB_validators.PB115_is_tasks_quiet_mode import (
    IsTasksQuietModeValidator,
```

2024-06-19 14:08 UTC, merged