Add PB108 to the new validate
demisto/demisto-sdk pull request #4359
Opened 2024-06-17 13:15 UTC by RotemAmit

## Related Issues
fixes:

## Description
Add PB108 to the new validate

2024-06-17 14:08 UTC, YuvHayun requested changes
Nice work.
See my comments.

2024-06-17 14:08 UTC, YuvHayun commented on .changelog/4359.yml
> +- description: Moved PB108 to the new validate
```suggestion
- description: Moved PB108 to the new validate format. The validate <what the validation does?>
```

2024-06-17 14:08 UTC, YuvHayun commented on demisto_sdk/commands/validate/validators/PB_validators/PB108_is_valid_task_id.py
> +    # expected_git_statuses = [GitStatuses.ADDED, GitStatuses.MODIFIED]
remove.

2024-06-17 14:08 UTC, YuvHayun commented on demisto_sdk/commands/validate/validators/PB_validators/PB108_is_valid_task_id.py
> +    description = "Validate that the task ID and the 'id' under the 'task' field are from UUID format"
```suggestion
    description = "Validate that the task ID and the 'id' under the 'task' field are from UUID format."
```

2024-06-17 14:08 UTC, YuvHayun commented on demisto_sdk/commands/validate/validators/PB_validators/PB108_is_valid_task_id.py
> +    rationale = ""
?

2024-06-17 14:08 UTC, YuvHayun commented on demisto_sdk/commands/validate/validators/PB_validators/PB108_is_valid_task_id.py
> +        return results
Let's make sure to return only one ValidationResult per contentitem.
Also, let's only mention the relevant fields that are not in the right format.
Consider alter **invalid_tasks** to return a dict of {"id": [malformed fields]}.

2024-06-18 06:44 UTC, YuvHayun approved these changes
Nice!
Minor comments.
Approved from my side.

2024-06-18 06:44 UTC, YuvHayun commented on demisto_sdk/commands/validate/validators/PB_validators/PB108_is_valid_task_id.py
> +                        message=tasks_error_message,
why not message=self.error_message.format(task_error_message)
where self.error_message = "This playbook has tasks with invalid 'taskid' or invalid 'id' under the 'task' field:\n{0}"?

2024-06-18 06:44 UTC, YuvHayun commented on demisto_sdk/commands/validate/validators/PB_validators/PB108_is_valid_task_id.py
> +            task = tasks[task_id]
```suggestion
        for task_id, task in tasks.items():
```

2024-06-18 07:22 UTC, Shellyber reviewed
Looking good, please see my comment before merging.

2024-06-18 07:22 UTC, Shellyber commented on demisto_sdk/commands/validate/validators/PB_validators/PB108_is_valid_task_id.py
> +    rationale = "Validate that the task ID and the 'id' under the 'task' field are from UUID format."
It shouldn't be the same. 
The rationale here is that each task should have a unique id to avoid unknown behavior and breaking the playbook

2024-06-18 08:19 UTC, merged