CR102 Validation Refactor
demisto/demisto-sdk pull request #4409
Opened 2024-07-08 13:35 UTC by noydavidi

## Related Issues
fixes:

## Description

2024-07-10 09:52 UTC, YuvHayun requested changes
Great job!
See my comments.

2024-07-10 09:52 UTC, YuvHayun commented on demisto_sdk/commands/validate/validators/CR_validators/CR102_validate_execution_mode_search_window.py
> +    rationale = ""
?

2024-07-10 09:52 UTC, YuvHayun commented on demisto_sdk/commands/validate/validators/CR_validators/CR102_validate_execution_mode_search_window.py
> +        return validation_results
Let's do this in list comprehension.

2024-07-10 09:52 UTC, YuvHayun commented on demisto_sdk/commands/content_graph/objects/correlation_rule.py
> +    execution_mode: Optional[str] = Field(None)
Let's make this field an enum with possible values 'REAL_TIME', 'SCHEDULED'.
You can see PlaybookTaskType in base_playbook object as a reference.
Make sure to fix the validation and test accordingly.

2024-07-10 09:52 UTC, YuvHayun commented on demisto_sdk/commands/validate/tests/CR_validators_test.py
> +    """
```suggestion
    When:
        Calling Validate.
    Then:
        The validation should fail.
    """
```

2024-07-10 09:52 UTC, YuvHayun commented on demisto_sdk/commands/validate/tests/CR_validators_test.py
> +        The validation should fail
```suggestion
        Calling Validate.
    Then:
        The validation should fail.
```

2024-07-10 09:52 UTC, YuvHayun commented on demisto_sdk/commands/validate/tests/CR_validators_test.py
> +        The validation should fail
```suggestion
        Calling Validate.
    Then:
        The validation should fail.
```

2024-07-11 07:05 UTC, YuvHayun approved these changes
Approved from my side.

2024-07-11 08:39 UTC, JudahSchwartz commented on demisto_sdk/commands/validate/validators/CR_validators/CR102_validate_execution_mode_search_window.py
> +                (not content_item.search_window)
a or a and b

is the same as just a
something looks weird with the logic here, double check this

2024-07-11 10:53 UTC, JudahSchwartz approved these changes

2024-07-11 12:55 UTC, merged