Ciac 11100 playbook run in build
demisto/demisto-sdk pull request #4658
Opened 2024-11-12 08:40 UTC by JasBeilin

## Related Issues
fixes:

## Description

2025-01-05 13:43 UTC, dantavori requested changes
some minor comments but looks very good!

2025-01-05 13:43 UTC, dantavori commented on pyproject.toml
> +
if there's no change then we can revert the changes in both poetry files

2025-01-05 13:43 UTC, dantavori commented on demisto_sdk/commands/test_content/test_use_case/test_use_case.py
> +        logging_module.info("Finished uploading test use case results file to bucket")
```suggestion
        logging_module.debug("Start uploading test use case results file to bucket")

        storage_client = storage.Client.from_service_account_json(self.service_account)
        storage_bucket = storage_client.bucket(self.artifacts_bucket)

        blob = storage_bucket.blob(
            f"content-test-use-case/{repository_name}/{file_name}"
        )
        blob.upload_from_filename(
            original_file_path.as_posix(),
            content_type="application/xml",
        )

        logging_module.debug("Finished uploading test use case results file to bucket")
```

2025-01-05 13:43 UTC, dantavori commented on demisto_sdk/commands/test_content/test_use_case/test_use_case.py
> +        logger.info("installing pyxdr...")
```suggestion
        logger.debug("installing pyxdr...")
```
generally go over everything and ensure logs are info only for "user messages" and not for "developer messages"
I recommend reading the job logs in the gitlab UI to easily understand which info logs we actually want to be debug

2025-01-05 13:43 UTC, dantavori commented on demisto_sdk/commands/test_content/test_use_case/test_use_case.py
> +            self.build_context.tests_data_keeper.errors = True
how does it behave in case of exception?
1. will the rest of the threads continue?
2. will we see the error message?

2025-01-05 13:43 UTC, dantavori commented on demisto_sdk/commands/test_content/test_use_case/tests/test_use_case_test.py
can we have one sanity E2E test (from the main command method)?

2025-01-06 12:30 UTC, eyalpalo commented on demisto_sdk/commands/common/clients/xsiam/xsiam_api_client.py
> +    def create_alert_from_json(self, json_content: dict) -> int:
I think we can leave it here as it offers another simple way to create alerts.

2025-01-06 12:39 UTC, eyalpalo commented on demisto_sdk/commands/common/clients/xsiam/xsiam_api_client.py
> +        return self._process_response(response, status_code, 200)
moved them to xsoar_client

2025-01-06 12:58 UTC, eyalpalo commented on demisto_sdk/commands/test_content/test_use_case/test_use_case.py
> +            self.build_context.tests_data_keeper.errors = True
yes, each thread should run its tests, the rest of the threads should keep running.
Also logs per thread are printed (with thread number)

2025-01-06 12:59 UTC, eyalpalo commented on demisto_sdk/commands/test_content/test_use_case/test_use_case.py
> +@app.command(
@Shellyber can you have a look please?

2025-01-06 13:43 UTC, Shellyber commented on demisto_sdk/commands/test_content/test_use_case/test_use_case.py
Please update the file_name to end with _setup.py at the end.
Also, keep the logic of the command options here and then the call to the command itself. 
The rest of the code - should be in a different file (the logic should be in a different file) - see examples in the other SDK commands (upload, download etc)

2025-01-06 13:57 UTC, eyalpalo commented on demisto_sdk/commands/test_content/tools.py
> +def tenant_config_cb(
both these commands were passed as is to this file as they were used both in the test modeling rules and test use case... can modify them to be better implemented...

2025-01-06 13:57 UTC, eyalpalo commented on demisto_sdk/commands/test_content/tools.py
> +def logs_token_cb(ctx: typer.Context, param: typer.CallbackParam, value: Optional[str]):
correct

2025-01-16 10:42 UTC, eyalpalo commented on demisto_sdk/commands/test_content/test_use_case/tests/test_use_case_test.py
Not sure its needed, the methods are tested in unit tests.

2025-01-17 11:33 UTC, kobymeir requested changes

2025-01-17 11:33 UTC, kobymeir commented on demisto_sdk/commands/common/clients/__init__.py
> +def parse_str_to_dict(input_str):
typing?

2025-01-17 11:33 UTC, kobymeir commented on demisto_sdk/commands/common/clients/__init__.py
> +def get_client_conf_from_pytest_request(request):
typing?

2025-01-17 11:33 UTC, kobymeir commented on demisto_sdk/commands/common/clients/xsiam/xsiam_api_client.py
> +        # type: ignore[attr-defined]
look like the type ignore isn't attached to any line

2025-01-17 11:33 UTC, kobymeir commented on demisto_sdk/commands/common/clients/xsiam/xsiam_api_client.py
> +            alert_uuids = []
```suggestion
        alert_uuids =  alert_uuids or []
```

2025-01-17 11:33 UTC, kobymeir commented on demisto_sdk/commands/common/clients/xsoar/xsoar_api_client.py
> +                    api_response = (
why?

2025-01-17 11:33 UTC, kobymeir commented on demisto_sdk/commands/test_content/test_use_case/template_file.py
> +    yield client_obj
why yield?

2025-01-17 11:33 UTC, kobymeir commented on demisto_sdk/commands/test_content/test_use_case/template_file.py
> +def api_client(client_conf):
typing?

2025-01-17 11:33 UTC, kobymeir commented on demisto_sdk/commands/test_content/test_use_case/template_file.py
> +        assert a is not None
teach them to use comments
```suggestion
        assert a is not None, "list_indicators should not be None"
```

2025-01-17 11:33 UTC, kobymeir commented on demisto_sdk/commands/test_content/test_use_case/template_file.py
> +        """Test feature two"""
teach them to use Given-When-Then approach.

2025-01-17 11:33 UTC, kobymeir commented on demisto_sdk/commands/test_content/test_use_case/test_use_case.py
> +    source_conftest = Path(f"{CONTENT_PATH}/Tests/scripts/dev_envs/pytest/conftest.py")
why not using Pathlib for path concatenation?

2025-01-26 18:21 UTC, dantavori approved these changes
as discussed, consider adding an E2E test (or at least cover the uncovered lines)

2025-01-26 18:21 UTC, dantavori commented on demisto_sdk/commands/common/git_util.py
> +                    Path(os.path.join(item.a_path))  # type: ignore
do you get a mypy failure without it? can we add type hints instead?

2025-01-27 08:14 UTC, eyalpalo commented on demisto_sdk/commands/common/git_util.py
> +                    Path(os.path.join(item.a_path))  # type: ignore
Its a library module... which has typing str|None... this is the reason for the mypy failure

2025-01-27 14:09 UTC, kobymeir approved these changes

2025-01-28 08:26 UTC, merged