fix rm108 by removing conent-assets absulote-link
demisto/demisto-sdk pull request #4683
Opened 2024-11-26 08:24 UTC by maimorag

## Related Issues
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-10606 

## Description
removing absolute links that contains "content-assests"

2025-01-16 08:41 UTC, YuvHayun approved these changes
Great work!
Approved from my side.

2025-01-16 08:41 UTC, YuvHayun commented on .changelog/4683.yml
> +- description: Fixed an issue where content-assets absolute paths raised an error from RM108 validation.
```suggestion
- description: Fixed RM108 validation to allow absolute paths if the files are a part of content-assets.
```

2025-01-16 08:41 UTC, YuvHayun commented on demisto_sdk/commands/validate/tests/RM_validators_test.py
> +    demisto_sdk/commands/validate/sdk_validation_config.toml
```suggestion
    demisto_sdk/commands/validate/sdk_validation_config.toml
```
?

2025-01-16 08:41 UTC, YuvHayun commented on demisto_sdk/commands/validate/tests/RM_validators_test.py
> +            2. description contains relative path that saved not under dec_files.
```suggestion
            1. invalid readme that contains absolute path.
            2. description contains relative path that saved not under dec_files.
```

Let's list the exact files that are given and the ones that are invalid - will be better for documenting the expected behavior.

2025-01-16 09:54 UTC, maimorag commented on demisto_sdk/commands/validate/tests/RM_validators_test.py
> +    demisto_sdk/commands/validate/sdk_validation_config.toml
by mistake

2025-01-19 14:36 UTC, eyalpalo requested changes

2025-01-19 14:36 UTC, eyalpalo commented on demisto_sdk/commands/validate/tests/RM_validators_test.py
> +        2. invalid description contains relative path that saved not under doc_files. For example:
```suggestion
        2. An invalid description contains a relative path not saved under doc_files. For example:
```
Please edit other descriptions as suggested here.

2025-01-19 14:36 UTC, eyalpalo commented on demisto_sdk/commands/validate/validators/RM_validators/RM108_is_image_path_valid.py
> +            if not re.search(DOC_FILE_IMAGE_REGEX, rel_img)
Why are we changing this?

2025-01-19 14:36 UTC, eyalpalo commented on demisto_sdk/commands/validate/validators/RM_validators/RM108_is_image_path_valid.py
> +                )
Let's refactor this code. It is very unclear.
Also, why store the link in a tuple?

2025-01-20 08:30 UTC, maimorag commented on demisto_sdk/commands/validate/validators/RM_validators/RM108_is_image_path_valid.py
> +                )
Tuples are generally faster and more memory-efficient, plus I don't need to make changes to the items.
https://www.simplilearn.com/difference-between-list-and-tuple-in-python-article#:~:text=Tuples%20are%20generally%20faster%20and,when%20iteration%20speed%20is%20crucial.

2025-01-20 13:58 UTC, maimorag commented on demisto_sdk/commands/validate/validators/RM_validators/RM108_is_image_path_valid.py
> +            if not re.search(DOC_FILE_IMAGE_REGEX, rel_img)
The change from re.match to re.search was necessary because re.match only checks for the pattern at the start of the string, whereas re.search looks for the pattern anywhere in the string. (for example ../../doc_files / ../../../doc_files /doc)

This ensures all occurrences of the pattern are correctly matched, regardless of where they appear in the string.

2025-01-20 15:20 UTC, merged