Convert PB121 to new validate
demisto/demisto-sdk pull request #4702
Opened 2024-12-05 15:21 UTC by jlevypaloalto

## Related Issues
fixes:

## Description

2024-12-31 13:04 UTC, YuvHayun requested changes
Looks good!
I added some comments.
Also, in general, please make sure to add documentation to all functions you're using and note the naming of the functions indeed makes sense according to the function return variable.

2024-12-31 13:04 UTC, YuvHayun commented on demisto_sdk/commands/validate/validators/PB_validators/PB121_is_correct_value_references_interface.py
> +    def is_valid_condition_task(self, task: TaskConfig) -> list[str]:
let's change the name to maybe obtain_invalid_contdition_tasks

2024-12-31 13:04 UTC, YuvHayun commented on demisto_sdk/commands/validate/validators/PB_validators/PB121_is_correct_value_references_interface.py
> +    def is_valid_regular_task(self, task: TaskConfig) -> list[str]:
let's rename to obtain_invalid regular_tasks or something similar,
makes more sense when when we're returning a list of invalid vlues.

2024-12-31 13:15 UTC, jlevypaloalto commented on demisto_sdk/commands/validate/validators/PB_validators/PB121_is_correct_value_references_interface.py
> +    fix_message = "Fixed the following inputs:\n"
I do, this is just a template

2024-12-31 13:18 UTC, jlevypaloalto commented on demisto_sdk/commands/validate/validators/PB_validators/PB121_is_correct_value_references_interface.py
> +            for value in (values or "").split(",")
I was considering the case where the `values` param is `None`. I can't accept this change because it doesn't account for that.

2024-12-31 13:19 UTC, jlevypaloalto commented on demisto_sdk/commands/validate/validators/PB_validators/PB121_is_correct_value_references_interface.py
> +            value_obj = value_obj or {}
[same](https://github.com/demisto/demisto-sdk/pull/4702/files#r1900109775)

2024-12-31 13:20 UTC, jlevypaloalto commented on demisto_sdk/commands/validate/validators/PB_validators/PB121_is_correct_value_references_interface.py
> +        elif value := getattr(value_obj, key, None):
I'll add an edge case catch.

2024-12-31 13:23 UTC, jlevypaloalto commented on demisto_sdk/commands/validate/validators/PB_validators/PB121_is_correct_value_references_interface.py
> +        invalid_values = self.obtain_invalid_playbook_inputs(content_item)
I considered keeping a list but it will complicate other logic.

2025-01-02 09:16 UTC, YuvHayun approved these changes
looks good!
Approved with 1 minor comment.

2025-01-02 09:16 UTC, YuvHayun commented on demisto_sdk/commands/validate/validators/PB_validators/PB121_is_correct_value_references_interface.py
> +        elif value := getattr(value_obj, key, None):
I meant that if the value is None and this is a dict then we'll end up attempting to use getattr on a dict. I think that the best solution here would be a nested condition in the if statement.

2025-01-07 11:15 UTC, merged