Add firstCreated Field
demisto/demisto-sdk pull request #4707
Opened 2024-12-11 11:00 UTC by BEAdi

## Related Issues
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-9534

## Description
Added the `firstCreated` in addition to the `created` field since the original is now a system field.

2024-12-29 14:31 UTC, jbabazadeh requested changes
great work please fix the tests

2024-12-29 14:31 UTC, jbabazadeh commented on .changelog/4707.yml
> +- description: Fixed an issue where the created date would conflict with the new XSOAR system field with the same name.
add the solution. that we adding a new field firstCreated

2024-12-31 10:48 UTC, BEAdi commented on demisto_sdk/commands/common/git_util.py
> +        return self.repo.index.commit(commit_message)
For the `test_get_file_creation_date` test, in order to check that the commit time is the same as we return.

2025-03-31 17:24 UTC, closed without merging

2025-06-12 17:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/demisto/demisto-sdk?pullRequest=4707) <br/>All committers have signed the CLA.