Convert IF118 to new validate
demisto/demisto-sdk pull request #4748
Opened 2024-12-31 16:10 UTC by jlevypaloalto

## Related Issues
fixes:

## Description

2025-01-02 07:36 UTC, YuvHayun requested changes
Nice work!
Minor comments

2025-01-02 07:36 UTC, YuvHayun commented on demisto_sdk/commands/validate/sdk_validation_config.toml
> +  "IF118",
remove from ignorable errors.

2025-01-02 07:36 UTC, YuvHayun commented on demisto_sdk/commands/validate/validators/IF_validators/IF118_is_alias_inner_alias_valid.py
> +    expected_git_statuses = [GitStatuses.ADDED, GitStatuses.MODIFIED]
```suggestion
```
You can remove it, that way it'll run whenever -g is given

2025-01-02 07:36 UTC, YuvHayun commented on demisto_sdk/commands/validate/tests/IF_validators_test.py
> +                {"cliName": "alias_1", "aliases": []},
should we fail this if the aliases list is empty? what's the behavior of the old validation?

2025-01-02 08:41 UTC, jlevypaloalto commented on demisto_sdk/commands/validate/tests/IF_validators_test.py
> +                {"cliName": "alias_1", "aliases": []},
This is the same behavior, it won't exist if it's empty

2025-01-05 10:49 UTC, YuvHayun approved these changes
Nice job! approved from my side.

2025-01-07 11:15 UTC, merged