sdk validate script id
demisto/demisto-sdk pull request #888
Opened 2020-11-22 09:08 UTC by abaumgarten

#Status
- [] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/30564

## Description
Added a check to demisto-sdk validate. Detects if an invalid script id being used in a playbook.

## Must have
- [x] Tests
- [x] Documentation

2020-11-22 09:56 UTC, guykeller requested changes

2020-11-22 09:56 UTC, guykeller commented on demisto_sdk/commands/common/errors.py
> +        return f'The following script id is not valid {script_entry_to_check}'
```suggestion
        return f'The following script id is not valid: {script_entry_to_check}'
```

2020-11-22 09:56 UTC, guykeller commented on demisto_sdk/commands/common/hook_validations/playbook.py
> +            skip_dependencies: whether dependencies should be skipped
please expand this description, it currently doesn't add any more detailed data than the name of the argument

2020-11-22 09:56 UTC, guykeller commented on demisto_sdk/commands/common/hook_validations/playbook.py
> +    def is_script_id_valid(self, skip_dependencies=False):
let's make this function shorter and easier to read - let's talk

2020-11-22 09:56 UTC, guykeller commented on demisto_sdk/commands/common/hook_validations/playbook.py
> +        if not id_set:
Shouldn't this case cause an exception?
When would this case happen? When does ID set creation fail?

2020-11-22 09:56 UTC, guykeller commented on demisto_sdk/commands/common/hook_validations/playbook.py
> +        all_scripts_from_id_set = id_set.get("scripts")
```suggestion
        id_set_scripts = id_set.get("scripts")
```

2020-11-22 09:56 UTC, guykeller commented on demisto_sdk/commands/common/hook_validations/playbook.py
> +        all_tasks_from_pb = self.current_file.get('tasks', {})
Removing words that add no further information
```suggestion
        pb_tasks = self.current_file.get('tasks', {})
```

2020-11-22 09:56 UTC, guykeller commented on demisto_sdk/commands/common/hook_validations/playbook.py
> +            pb_task = task.get('task', {})
how is it different from `task`?

2020-11-22 09:56 UTC, guykeller commented on demisto_sdk/commands/common/hook_validations/playbook.py
> +            pb_script = pb_task.get('script')
```suggestion
            script_used_in_task = pb_task.get('script')
```

2020-11-22 09:56 UTC, guykeller commented on demisto_sdk/commands/common/hook_validations/playbook.py
> +            script_entry_to_check = pb_script if not None else pb_script_name
`if not None` this is a deterministic assignment

2020-11-22 09:56 UTC, guykeller commented on demisto_sdk/commands/common/hook_validations/playbook.py
> +                     for key in id_set_dict])
this code could be made more readable

2020-11-22 09:56 UTC, guykeller commented on demisto_sdk/commands/common/hook_validations/playbook.py
> +    def get_id_set_file(self, skip_dependencies):
Is there no such existing functionality anywhere that we can borrow?
Maybe @roysagi knows?

2020-11-22 09:56 UTC, guykeller commented on demisto_sdk/commands/common/tests/playbook_test.py
> +        - In case script id or script name is does not exist in id_set , prints a warning.
```suggestion
        - In case script id or script name don't exist in id_set , prints a warning.
```

2020-11-22 09:56 UTC, guykeller commented on demisto_sdk/commands/common/tools.py
> +    return id_set
why not use `finally` then?

2020-11-24 12:00 UTC, roysagi requested changes

2020-11-24 12:00 UTC, roysagi commented on demisto_sdk/commands/common/hook_validations/playbook.py
> +            integration_script_flag = "|||"
leave a note explaining what is this "flag"

2020-11-24 12:03 UTC, abaumgarten commented on demisto_sdk/commands/common/errors.py
> +        return f'The following script id is not valid: {script_entry_to_check}'
@roysagi  it says that script id is not valid. Should I write that the id suppose to appear in id_set?

2020-11-24 12:11 UTC, abaumgarten commented on demisto_sdk/commands/common/hook_validations/playbook.py
> +        if not id_set_path or not os.path.isfile(id_set_path):
@roysagi I can't find the flag you are talking about, how can I get it?

2020-11-24 13:40 UTC, roysagi commented on demisto_sdk/commands/common/errors.py
> +        return f'The following script id is not valid: {script_entry_to_check}'
If possible yes, though how could you determine what is the right ID? I think more to the likes of:

f"in task {id} the script {script_name/id} was not found in the id_set.json file. Please make sure:\n"
f"1 - The right script id is set and the spelling is correct.\n"
f"2 - The id_set.json file is up to date. Delete the file by running: `rm -rf Tests/id_set.json` and rerun the command."

2020-11-24 13:40 UTC, roysagi commented on demisto_sdk/commands/common/hook_validations/playbook.py
> +        if not id_set_path or not os.path.isfile(id_set_path):
![image](https://user-images.githubusercontent.com/50295826/100101741-50635e80-2e6b-11eb-95f4-d18da5652da4.png)

found in main, passed to the ValidateManager and you should use it here.

2020-11-25 13:50 UTC, roysagi approved these changes
Looks good, please do check on some local builds using this branch before merging and address my final comment.

2020-11-25 14:55 UTC, abaumgarten commented on demisto_sdk/commands/validate/validate_manager.py
> +        id_set = None
Done

2020-11-25 15:15 UTC, guykeller requested changes

2020-11-25 15:31 UTC, abaumgarten commented on demisto_sdk/commands/common/hook_validations/playbook.py
> +                    return is_valid
I think that is a convention , because this if statement appears many times in this file , for the same purpose.

2020-11-25 15:31 UTC, abaumgarten commented on demisto_sdk/commands/common/hook_validations/playbook.py
> +            pb_script_name = pb_task.get('scriptName')
Done

2020-11-25 15:31 UTC, abaumgarten commented on demisto_sdk/commands/common/hook_validations/playbook.py
> +            script_entry_to_check = script_used_in_task if script_used_in_task else pb_script_name
Done

2020-11-25 15:31 UTC, abaumgarten commented on demisto_sdk/commands/common/hook_validations/playbook.py
> +            if script_used_in_task and integration_script_flag not in script_used_in_task:
Done

2020-11-29 08:55 UTC, guykeller approved these changes

2020-11-29 09:01 UTC, merged